/**
 * 한자 사전 데이터 (hanja-dict.js)
 * 자평진전(子平眞詮)에 등장하는 주요 한자의 음/뜻/부수/획수
 *
 * 구조: { '한자': { eumhun: '음', meaning: '뜻', radical: '부수', strokes: 총획수, myeongri: '명리학적 의미(선택)' } }
 */

const HANJA_DICT = {
  // ═══════════════════════════════════════════
  // 천간 (天干) - 10 Heavenly Stems
  // ═══════════════════════════════════════════
  '甲': { eumhun: '갑', meaning: '갑옷, 첫째 천간', radical: '田', strokes: 5, myeongri: '양목(陽木). 큰 나무, 대들보. 봄의 시작, 동쪽. 인성이 곧고 강직함' },
  '乙': { eumhun: '을', meaning: '둘째 천간, 새', radical: '乙', strokes: 1, myeongri: '음목(陰木). 풀, 덩굴, 꽃. 유연하고 감싸는 성질. 봄, 동쪽' },
  '丙': { eumhun: '병', meaning: '셋째 천간, 밝다', radical: '一', strokes: 5, myeongri: '양화(陽火). 태양, 큰 불. 밝고 화려함. 여름, 남쪽' },
  '丁': { eumhun: '정', meaning: '넷째 천간, 장정', radical: '一', strokes: 2, myeongri: '음화(陰火). 촛불, 등불, 별빛. 문명의 불. 여름, 남쪽' },
  '戊': { eumhun: '무', meaning: '다섯째 천간', radical: '戈', strokes: 5, myeongri: '양토(陽土). 산, 제방, 큰 언덕. 중앙, 사계절의 변환점. 포용력' },
  '己': { eumhun: '기', meaning: '여섯째 천간, 자기', radical: '己', strokes: 3, myeongri: '음토(陰土). 전답, 정원. 만물을 기르는 땅. 중앙' },
  '庚': { eumhun: '경', meaning: '일곱째 천간', radical: '广', strokes: 8, myeongri: '양금(陽金). 큰 쇠, 도끼, 칼. 가을, 서쪽. 결단력, 의리' },
  '辛': { eumhun: '신', meaning: '여덟째 천간, 매울', radical: '辛', strokes: 7, myeongri: '음금(陰金). 보석, 바늘, 가위. 가을, 서쪽. 세밀함, 예리함' },
  '壬': { eumhun: '임', meaning: '아홉째 천간', radical: '士', strokes: 4, myeongri: '양수(陽水). 큰 바다, 강, 호수. 겨울, 북쪽. 지혜, 유동성' },
  '癸': { eumhun: '계', meaning: '열째 천간', radical: '癶', strokes: 12, myeongri: '음수(陰水). 이슬, 비, 안개. 겨울, 북쪽. 상상력, 내면의 지혜' },

  // ═══════════════════════════════════════════
  // 지지 (地支) - 12 Earthly Branches
  // ═══════════════════════════════════════════
  '子': { eumhun: '자', meaning: '아들, 자식, 첫째 지지', radical: '子', strokes: 3, myeongri: '쥐(鼠). 양수(陽水). 11월, 북쪽. 자시(23:00-01:00). 장생(長生)의 시작' },
  '丑': { eumhun: '축', meaning: '둘째 지지, 소', radical: '一', strokes: 4, myeongri: '소(牛). 음토(陰土). 12월, 북동쪽. 축시(01:00-03:00). 습토, 금의 고(庫)' },
  '寅': { eumhun: '인', meaning: '셋째 지지, 범', radical: '宀', strokes: 11, myeongri: '호랑이(虎). 양목(陽木). 1월, 동북쪽. 인시(03:00-05:00). 봄의 시작' },
  '卯': { eumhun: '묘', meaning: '넷째 지지, 토끼', radical: '卩', strokes: 5, myeongri: '토끼(兎). 음목(陰木). 2월, 동쪽. 묘시(05:00-07:00). 꽃이 피는 때' },
  '辰': { eumhun: '진', meaning: '다섯째 지지, 별', radical: '辰', strokes: 7, myeongri: '용(龍). 양토(陽土). 3월, 동남쪽. 진시(07:00-09:00). 습토, 수의 고(庫)' },
  '巳': { eumhun: '사', meaning: '여섯째 지지, 뱀', radical: '己', strokes: 3, myeongri: '뱀(蛇). 음화(陰火). 4월, 남동쪽. 사시(09:00-11:00). 여름의 시작' },
  '午': { eumhun: '오', meaning: '일곱째 지지, 말', radical: '十', strokes: 4, myeongri: '말(馬). 양화(陽火). 5월, 남쪽. 오시(11:00-13:00). 한여름, 도화살' },
  '未': { eumhun: '미', meaning: '여덟째 지지, 양', radical: '木', strokes: 5, myeongri: '양(羊). 음토(陰土). 6월, 남서쪽. 미시(13:00-15:00). 건토, 목의 고(庫)' },
  '申': { eumhun: '신', meaning: '아홉째 지지, 원숭이', radical: '田', strokes: 5, myeongri: '원숭이(猴). 양금(陽金). 7월, 서남쪽. 신시(15:00-17:00). 가을의 시작' },
  '酉': { eumhun: '유', meaning: '열째 지지, 닭', radical: '酉', strokes: 7, myeongri: '닭(鷄). 음금(陰金). 8월, 서쪽. 유시(17:00-19:00). 도화살' },
  '戌': { eumhun: '술', meaning: '열한째 지지, 개', radical: '戈', strokes: 6, myeongri: '개(犬). 양토(陽土). 9월, 서북쪽. 술시(19:00-21:00). 건토, 화의 고(庫)' },
  '亥': { eumhun: '해', meaning: '열두째 지지, 돼지', radical: '亠', strokes: 6, myeongri: '돼지(豬). 음수(陰水). 10월, 북서쪽. 해시(21:00-23:00). 겨울의 시작' },

  // ═══════════════════════════════════════════
  // 오행 (五行) - Five Elements
  // ═══════════════════════════════════════════
  '木': { eumhun: '목', meaning: '나무', radical: '木', strokes: 4, myeongri: '오행의 하나. 봄, 동쪽, 청색, 인묘(寅卯). 생장, 발전, 인(仁)의 덕' },
  '火': { eumhun: '화', meaning: '불', radical: '火', strokes: 4, myeongri: '오행의 하나. 여름, 남쪽, 적색, 사오(巳午). 광명, 예(禮)의 덕' },
  '土': { eumhun: '토', meaning: '흙, 땅', radical: '土', strokes: 3, myeongri: '오행의 하나. 사계 전환기, 중앙, 황색, 진술축미(辰戌丑未). 중재, 신(信)의 덕' },
  '金': { eumhun: '금', meaning: '쇠, 금', radical: '金', strokes: 8, myeongri: '오행의 하나. 가을, 서쪽, 백색, 신유(申酉). 결실, 의(義)의 덕' },
  '水': { eumhun: '수', meaning: '물', radical: '水', strokes: 4, myeongri: '오행의 하나. 겨울, 북쪽, 흑색, 해자(亥子). 저장, 지(智)의 덕' },

  // ═══════════════════════════════════════════
  // 십신 (十神) 관련 글자
  // ═══════════════════════════════════════════
  '比': { eumhun: '비', meaning: '견주다, 비교하다', radical: '比', strokes: 4, myeongri: '십신 중 비견(比肩). 나와 같은 오행, 같은 음양. 형제, 동료, 경쟁자' },
  '肩': { eumhun: '견', meaning: '어깨', radical: '肉', strokes: 8, myeongri: '비견(比肩)의 견. 어깨를 나란히 함, 대등한 관계' },
  '劫': { eumhun: '겁', meaning: '빼앗다, 겁탈하다', radical: '力', strokes: 7, myeongri: '십신 중 겁재(劫財). 나와 같은 오행, 다른 음양. 재물을 뺏는 힘' },
  '食': { eumhun: '식', meaning: '먹다, 음식', radical: '食', strokes: 9, myeongri: '십신 중 식신(食神). 내가 생하는 오행, 같은 음양. 의식주, 수명, 자식' },
  '神': { eumhun: '신', meaning: '귀신, 신령', radical: '示', strokes: 10, myeongri: '식신(食神), 용신(用神) 등에 사용. 신묘한 작용' },
  '傷': { eumhun: '상', meaning: '다치다, 상처', radical: '人', strokes: 13, myeongri: '십신 중 상관(傷官). 내가 생하는 오행, 다른 음양. 정관을 극하여 해침' },
  '官': { eumhun: '관', meaning: '벼슬, 관리', radical: '宀', strokes: 8, myeongri: '십신 중 정관(正官)/편관(偏官). 나를 극하는 오행. 직업, 명예, 규율' },
  '偏': { eumhun: '편', meaning: '치우치다, 한쪽', radical: '人', strokes: 11, myeongri: '편재, 편관, 편인 등에 사용. 음양이 같은 관계(무정한 관계)' },
  '正': { eumhun: '정', meaning: '바르다, 바를', radical: '止', strokes: 5, myeongri: '정재, 정관, 정인 등에 사용. 음양이 다른 관계(유정한 관계)' },
  '印': { eumhun: '인', meaning: '도장, 찍다', radical: '卩', strokes: 6, myeongri: '십신 중 정인(正印)/편인(偏印). 나를 생하는 오행. 학문, 문서, 어머니' },
  '財': { eumhun: '재', meaning: '재물, 재산', radical: '貝', strokes: 10, myeongri: '십신 중 정재(正財)/편재(偏財). 내가 극하는 오행. 재물, 아버지, 아내(남자)' },

  // ═══════════════════════════════════════════
  // 음양 (陰陽)
  // ═══════════════════════════════════════════
  '陰': { eumhun: '음', meaning: '그늘, 응달', radical: '阝', strokes: 11, myeongri: '만물의 어두운 면, 여성적 기운. 음간: 乙丁己辛癸. 음지: 丑卯巳未酉亥' },
  '陽': { eumhun: '양', meaning: '볕, 양달', radical: '阝', strokes: 12, myeongri: '만물의 밝은 면, 남성적 기운. 양간: 甲丙戊庚壬. 양지: 子寅辰午申戌' },

  // ═══════════════════════════════════════════
  // 격국 (格局) 관련
  // ═══════════════════════════════════════════
  '格': { eumhun: '격', meaning: '격식, 법칙', radical: '木', strokes: 10, myeongri: '사주의 격국(格局). 월지(月支)의 장간(藏干)이 천간에 투출하여 정해짐' },
  '局': { eumhun: '국', meaning: '판, 형국', radical: '尸', strokes: 7, myeongri: '격국(格局)의 국. 사주 전체의 구성과 형세' },
  '用': { eumhun: '용', meaning: '쓰다, 사용하다', radical: '用', strokes: 5, myeongri: '용신(用神). 사주에서 가장 필요한 글자. 격국을 성립시키는 핵심 오행' },
  '喜': { eumhun: '희', meaning: '기쁘다', radical: '口', strokes: 12, myeongri: '희신(喜神). 용신을 돕는 오행. 용신 다음으로 중요한 역할' },
  '忌': { eumhun: '기', meaning: '꺼리다, 싫어하다', radical: '心', strokes: 7, myeongri: '기신(忌神). 용신을 해치는 오행. 사주에서 나쁜 작용을 하는 글자' },
  '仇': { eumhun: '구', meaning: '원수', radical: '人', strokes: 4, myeongri: '구신(仇神). 기신을 돕는 오행. 간접적으로 용신을 해침' },
  '閑': { eumhun: '한', meaning: '한가하다', radical: '門', strokes: 12, myeongri: '한신(閑神). 용신에 대해 도움도 해도 안 되는 중립적 오행' },

  // ═══════════════════════════════════════════
  // 합 (合) 관련
  // ═══════════════════════════════════════════
  '合': { eumhun: '합', meaning: '합하다, 모으다', radical: '口', strokes: 6, myeongri: '천간합(天干合), 지지합(地支合). 두 글자가 서로 끌려 합쳐지는 관계' },
  '沖': { eumhun: '충', meaning: '충돌하다, 부딪치다', radical: '水', strokes: 7, myeongri: '지지충(地支沖). 서로 대립하여 부딪치는 관계. 변동, 이동, 갈등' },
  '刑': { eumhun: '형', meaning: '형벌', radical: '刀', strokes: 6, myeongri: '지지형(地支刑). 형벌의 관계. 삼형살, 자형 등. 법적 문제, 질병' },
  '破': { eumhun: '파', meaning: '깨뜨리다', radical: '石', strokes: 10, myeongri: '지지파(地支破). 깨뜨리는 관계. 파괴, 손실' },
  '害': { eumhun: '해', meaning: '해치다', radical: '宀', strokes: 10, myeongri: '지지해(地支害). 육해(六害). 서로 해치는 관계. 질병, 고통' },

  // ═══════════════════════════════════════════
  // 자평진전 핵심 용어 한자
  // ═══════════════════════════════════════════
  '命': { eumhun: '명', meaning: '목숨, 명령', radical: '口', strokes: 8, myeongri: '명(命). 사주팔자로 보는 운명. 명리학(命理學)의 명' },
  '理': { eumhun: '리/이', meaning: '다스리다, 이치', radical: '玉', strokes: 11, myeongri: '이치, 도리. 명리학(命理學)의 리. 사주의 이치를 연구하는 학문' },
  '學': { eumhun: '학', meaning: '배우다', radical: '子', strokes: 16, myeongri: '학문. 명리학(命理學), 자평학(子平學)' },
  '平': { eumhun: '평', meaning: '평평하다, 고르다', radical: '干', strokes: 5, myeongri: '자평(子平). 서자평(徐子平)의 이름에서 유래. 사주명리학의 다른 이름' },
  '眞': { eumhun: '진', meaning: '참, 진실', radical: '目', strokes: 10, myeongri: '자평진전(子平眞詮)의 진. 참된, 진실한 내용' },
  '詮': { eumhun: '전', meaning: '해석하다, 풀이', radical: '言', strokes: 13, myeongri: '자평진전(子平眞詮)의 전. 풀이, 해설. 자평의 참된 해설이라는 뜻' },
  '論': { eumhun: '론/논', meaning: '논하다, 의논하다', radical: '言', strokes: 15, myeongri: '자평진전 각 장의 제목에 사용. ~을 논하다' },

  // ═══════════════════════════════════════════
  // 생극 (生剋) 관련
  // ═══════════════════════════════════════════
  '生': { eumhun: '생', meaning: '나다, 살다', radical: '生', strokes: 5, myeongri: '상생(相生). 한 오행이 다른 오행을 낳아 도움. 木生火, 火生土, 土生金, 金生水, 水生木' },
  '剋': { eumhun: '극', meaning: '이기다, 극하다', radical: '刀', strokes: 9, myeongri: '상극(相剋). 한 오행이 다른 오행을 제압. 木剋土, 土剋水, 水剋火, 火剋金, 金剋木' },
  '克': { eumhun: '극', meaning: '이기다', radical: '儿', strokes: 7, myeongri: '剋의 약자. 상극(相克) 관계에서 사용' },
  '相': { eumhun: '상', meaning: '서로', radical: '目', strokes: 9, myeongri: '서로의 관계. 상생(相生), 상극(相剋)에 사용' },
  '洩': { eumhun: '설', meaning: '새다, 빠지다', radical: '水', strokes: 9, myeongri: '설기(洩氣). 기운이 빠져나감. 생하는 관계에서 생해주는 쪽의 기운이 약해짐' },

  // ═══════════════════════════════════════════
  // 사주 구성 요소
  // ═══════════════════════════════════════════
  '天': { eumhun: '천', meaning: '하늘', radical: '大', strokes: 4, myeongri: '천간(天干). 하늘의 기운. 사주에서 위쪽 글자(연간, 월간, 일간, 시간)' },
  '干': { eumhun: '간', meaning: '줄기, 방패', radical: '干', strokes: 3, myeongri: '천간(天干)의 간. 줄기. 하늘의 기둥' },
  '地': { eumhun: '지', meaning: '땅', radical: '土', strokes: 6, myeongri: '지지(地支). 땅의 기운. 사주에서 아래쪽 글자(연지, 월지, 일지, 시지)' },
  '支': { eumhun: '지', meaning: '가지, 지탱하다', radical: '支', strokes: 4, myeongri: '지지(地支)의 지. 가지. 땅의 가지' },
  '柱': { eumhun: '주', meaning: '기둥', radical: '木', strokes: 9, myeongri: '사주(四柱)의 주. 기둥. 년주, 월주, 일주, 시주의 네 기둥' },
  '四': { eumhun: '사', meaning: '넷', radical: '囗', strokes: 5, myeongri: '사주(四柱)의 사. 네 개의 기둥(년월일시)' },
  '八': { eumhun: '팔', meaning: '여덟', radical: '八', strokes: 2, myeongri: '팔자(八字)의 팔. 여덟 글자(천간 4 + 지지 4)' },
  '字': { eumhun: '자', meaning: '글자', radical: '子', strokes: 6, myeongri: '팔자(八字)의 자. 사주를 이루는 여덟 글자' },
  '年': { eumhun: '년/연', meaning: '해, 년', radical: '干', strokes: 6, myeongri: '년주(年柱). 태어난 해. 조상궁, 사회적 환경' },
  '月': { eumhun: '월', meaning: '달', radical: '月', strokes: 4, myeongri: '월주(月柱). 태어난 달. 부모궁, 격국을 정하는 핵심. 월령(月令)' },
  '日': { eumhun: '일', meaning: '날, 해', radical: '日', strokes: 4, myeongri: '일주(日柱). 태어난 날. 나 자신(일간=일원=일주). 배우자궁' },
  '時': { eumhun: '시', meaning: '때', radical: '日', strokes: 10, myeongri: '시주(時柱). 태어난 시간. 자녀궁, 말년운' },

  // ═══════════════════════════════════════════
  // 월령 (月令) / 절기 관련
  // ═══════════════════════════════════════════
  '令': { eumhun: '령/영', meaning: '명령, 하여금', radical: '人', strokes: 5, myeongri: '월령(月令). 월지가 가진 기운의 명령. 사주에서 가장 중요한 글자' },
  '旺': { eumhun: '왕', meaning: '왕성하다', radical: '日', strokes: 8, myeongri: '왕(旺)한 상태. 기운이 강성함. 월령을 얻으면 왕하다고 함' },
  '衰': { eumhun: '쇠', meaning: '쇠하다', radical: '衣', strokes: 10, myeongri: '쇠(衰)한 상태. 기운이 약해짐. 십이운성 중 하나' },
  '氣': { eumhun: '기', meaning: '기운', radical: '气', strokes: 10, myeongri: '기(氣). 오행의 기운. 사주에서 각 글자가 가진 에너지' },
  '勢': { eumhun: '세', meaning: '형세, 힘', radical: '力', strokes: 13, myeongri: '세(勢). 기세, 형세. 사주 전체의 흐름과 힘의 방향' },
  '得': { eumhun: '득', meaning: '얻다', radical: '彳', strokes: 11, myeongri: '득령(得令): 월령을 얻음, 득지(得地): 지지의 도움을 얻음' },
  '失': { eumhun: '실', meaning: '잃다', radical: '大', strokes: 5, myeongri: '실령(失令): 월령을 잃음. 일간이 월지에서 힘을 받지 못함' },

  // ═══════════════════════════════════════════
  // 십이운성 (十二運星) 관련
  // ═══════════════════════════════════════════
  '長': { eumhun: '장', meaning: '길다, 어른', radical: '長', strokes: 8, myeongri: '장생(長生). 십이운성의 첫째. 태어남, 시작. 생명력의 시작' },
  '沐': { eumhun: '목', meaning: '머리 감다', radical: '水', strokes: 7, myeongri: '목욕(沐浴). 십이운성. 씻김, 불안정, 도화(桃花)와 관련' },
  '浴': { eumhun: '욕', meaning: '목욕하다', radical: '水', strokes: 10, myeongri: '목욕(沐浴)의 욕. 목욕살. 변동, 이성문제' },
  '冠': { eumhun: '관', meaning: '갓, 관', radical: '冖', strokes: 9, myeongri: '관대(冠帶). 십이운성. 갓을 쓰는 나이. 성장, 독립' },
  '帶': { eumhun: '대', meaning: '띠, 차다', radical: '巾', strokes: 11, myeongri: '관대(冠帶)의 대. 허리띠를 매다. 성인이 됨' },
  '臨': { eumhun: '임', meaning: '임하다, 다가가다', radical: '臣', strokes: 17, myeongri: '임관(臨官). 십이운성. 벼슬에 나아감. 사회 진출, 활동력' },
  '帝': { eumhun: '제', meaning: '임금', radical: '巾', strokes: 9, myeongri: '제왕(帝旺). 십이운성. 최고의 왕성한 상태' },
  '死': { eumhun: '사', meaning: '죽다', radical: '歹', strokes: 6, myeongri: '사(死). 십이운성. 기운이 끝남. 고정, 정지' },
  '墓': { eumhun: '묘', meaning: '무덤', radical: '土', strokes: 13, myeongri: '묘(墓)/고(庫). 십이운성. 저장, 수집. 묘지(창고)에 들어감' },
  '絶': { eumhun: '절', meaning: '끊다, 끊어지다', radical: '糸', strokes: 12, myeongri: '절(絶). 십이운성. 기운이 완전히 끊어짐. 새로운 변화의 전조' },
  '胎': { eumhun: '태', meaning: '아이 밸', radical: '肉', strokes: 9, myeongri: '태(胎). 십이운성. 잉태, 새 생명의 시작. 계획, 구상 단계' },
  '養': { eumhun: '양', meaning: '기르다', radical: '食', strokes: 15, myeongri: '양(養). 십이운성. 양육, 준비 단계. 어머니 뱃속에서 자람' },
  '病': { eumhun: '병', meaning: '병, 앓다', radical: '疒', strokes: 10, myeongri: '병(病). 십이운성. 기운이 약해져 병듦. 쇠약, 고민' },

  // ═══════════════════════════════════════════
  // 장간 (藏干) 관련
  // ═══════════════════════════════════════════
  '藏': { eumhun: '장/창', meaning: '감추다, 창고', radical: '艸', strokes: 18, myeongri: '장간(藏干). 지지 속에 감추어진 천간. 지지의 본기/중기/여기' },
  '透': { eumhun: '투', meaning: '통하다, 드러나다', radical: '辵', strokes: 14, myeongri: '투출(透出). 장간이 천간에 드러남. 격국을 정하는 핵심 조건' },
  '出': { eumhun: '출', meaning: '나다, 나가다', radical: '凵', strokes: 5, myeongri: '투출(透出)의 출. 드러남. 장간이 천간에 나타남' },
  '本': { eumhun: '본', meaning: '근본, 뿌리', radical: '木', strokes: 5, myeongri: '본기(本氣). 지지에 가장 강하게 들어있는 천간' },
  '中': { eumhun: '중', meaning: '가운데', radical: '丨', strokes: 4, myeongri: '중기(中氣). 지지에 두 번째로 들어있는 천간' },
  '餘': { eumhun: '여', meaning: '남다, 나머지', radical: '食', strokes: 16, myeongri: '여기(餘氣). 지지에 세 번째로 들어있는 천간. 이전 월의 잔여 기운' },

  // ═══════════════════════════════════════════
  // 자평진전 주요 논제 관련 한자
  // ═══════════════════════════════════════════
  '體': { eumhun: '체', meaning: '몸, 본체', radical: '骨', strokes: 23, myeongri: '체(體). 사주의 본체. 일간, 격국 등 사주의 기본 틀' },
  '配': { eumhun: '배', meaning: '짝, 배합하다', radical: '酉', strokes: 10, myeongri: '배합(配合). 사주 글자 간의 조합과 궁합' },
  '取': { eumhun: '취', meaning: '취하다, 가지다', radical: '又', strokes: 8, myeongri: '취용(取用). 용신을 취함. 격국에서 용신을 정하는 것' },
  '成': { eumhun: '성', meaning: '이루다', radical: '戈', strokes: 7, myeongri: '성격(成格). 격국이 이루어짐. 좋은 구성의 사주' },
  '敗': { eumhun: '패', meaning: '패하다, 무너지다', radical: '攴', strokes: 11, myeongri: '패격(敗格)/파격(破格). 격국이 깨짐. 나쁜 구성의 사주' },
  '清': { eumhun: '청', meaning: '맑다', radical: '水', strokes: 11, myeongri: '청(清). 사주가 맑고 깨끗함. 격국이 순수하여 좋은 구성' },
  '濁': { eumhun: '탁', meaning: '흐리다', radical: '水', strokes: 16, myeongri: '탁(濁). 사주가 혼탁함. 격국이 복잡하여 나쁜 구성' },
  '順': { eumhun: '순', meaning: '순하다, 따르다', radical: '頁', strokes: 12, myeongri: '순용(順用). 용신을 순하게 씀. 상생의 방식으로 용신을 취함' },
  '逆': { eumhun: '역', meaning: '거스르다', radical: '辵', strokes: 10, myeongri: '역용(逆用). 용신을 거슬러 씀. 상극의 방식으로 용신을 취함' },
  '變': { eumhun: '변', meaning: '변하다', radical: '言', strokes: 23, myeongri: '변화(變化). 합, 충 등으로 인한 오행의 변화' },
  '化': { eumhun: '화', meaning: '되다, 변화하다', radical: '匕', strokes: 4, myeongri: '화(化). 합화(合化). 천간합이 되어 다른 오행으로 변하는 것' },

  // ═══════════════════════════════════════════
  // 운 (運) 관련
  // ═══════════════════════════════════════════
  '運': { eumhun: '운', meaning: '운, 움직이다', radical: '辵', strokes: 13, myeongri: '대운(大運), 세운(歲運). 시간의 흐름에 따른 기운의 변화' },
  '大': { eumhun: '대', meaning: '크다', radical: '大', strokes: 3, myeongri: '대운(大運). 10년 단위의 운. 월주에서 파생되어 순행/역행' },
  '歲': { eumhun: '세', meaning: '해, 나이', radical: '止', strokes: 13, myeongri: '세운(歲運)/유년(流年). 매년 돌아오는 운. 그 해의 천간지지' },
  '流': { eumhun: '류/유', meaning: '흐르다', radical: '水', strokes: 10, myeongri: '유년(流年). 흘러가는 해. 매년 바뀌는 운세' },

  // ═══════════════════════════════════════════
  // 부성/모성/처재/자식 등 육친 관련
  // ═══════════════════════════════════════════
  '父': { eumhun: '부', meaning: '아버지', radical: '父', strokes: 4, myeongri: '아버지. 남자에게는 편재(偏財), 여자에게는 정재(正財)로 봄' },
  '母': { eumhun: '모', meaning: '어머니', radical: '毋', strokes: 5, myeongri: '어머니. 정인(正印)으로 봄. 양육, 보호, 학문의 상징' },
  '妻': { eumhun: '처', meaning: '아내', radical: '女', strokes: 8, myeongri: '아내. 남자에게 정재(正財)로 봄' },
  '夫': { eumhun: '부', meaning: '남편, 지아비', radical: '大', strokes: 4, myeongri: '남편. 여자에게 정관(正官)으로 봄' },
  '兄': { eumhun: '형', meaning: '형', radical: '儿', strokes: 5, myeongri: '형제자매. 비겁(比劫)으로 봄' },
  '弟': { eumhun: '제', meaning: '아우', radical: '弓', strokes: 7, myeongri: '동생. 비겁(比劫)으로 봄' },
  '子': { eumhun: '자', meaning: '아들, 자식', radical: '子', strokes: 3, myeongri: '자녀. 남자에게 관살(官殺), 여자에게 식상(食傷)으로 봄' },

  // ═══════════════════════════════════════════
  // 일반 한자 (자평진전 빈출)
  // ═══════════════════════════════════════════
  '之': { eumhun: '지', meaning: '~의, 가다', radical: '丿', strokes: 4 },
  '也': { eumhun: '야', meaning: '~이다, ~도', radical: '乙', strokes: 3 },
  '者': { eumhun: '자', meaning: '~하는 사람/것', radical: '老', strokes: 8 },
  '而': { eumhun: '이', meaning: '~하고, 그러나', radical: '而', strokes: 6 },
  '以': { eumhun: '이', meaning: '~으로써', radical: '人', strokes: 5 },
  '爲': { eumhun: '위', meaning: '하다, 되다', radical: '爪', strokes: 12 },
  '不': { eumhun: '불/부', meaning: '아니다', radical: '一', strokes: 4 },
  '有': { eumhun: '유', meaning: '있다', radical: '月', strokes: 6 },
  '無': { eumhun: '무', meaning: '없다', radical: '火', strokes: 12 },
  '可': { eumhun: '가', meaning: '가하다, 옳다', radical: '口', strokes: 5 },
  '能': { eumhun: '능', meaning: '능하다, 할 수 있다', radical: '肉', strokes: 10 },
  '如': { eumhun: '여', meaning: '같다, 만약', radical: '女', strokes: 6 },
  '若': { eumhun: '약', meaning: '만약, 같다', radical: '艸', strokes: 8 },
  '則': { eumhun: '칙/즉', meaning: '곧, 법칙', radical: '刀', strokes: 9 },
  '其': { eumhun: '기', meaning: '그, 그것', radical: '八', strokes: 8 },
  '此': { eumhun: '차', meaning: '이것', radical: '止', strokes: 6 },
  '是': { eumhun: '시', meaning: '이것, 옳다', radical: '日', strokes: 9 },
  '非': { eumhun: '비', meaning: '아니다', radical: '非', strokes: 8 },
  '所': { eumhun: '소', meaning: '바, 곳', radical: '戶', strokes: 8 },
  '於': { eumhun: '어', meaning: '~에, ~에서', radical: '方', strokes: 8 },
  '與': { eumhun: '여', meaning: '~와, 주다', radical: '臼', strokes: 14 },
  '為': { eumhun: '위', meaning: '하다, 되다', radical: '爪', strokes: 9 },
  '從': { eumhun: '종', meaning: '따르다', radical: '彳', strokes: 11 },
  '自': { eumhun: '자', meaning: '스스로', radical: '自', strokes: 6 },
  '乃': { eumhun: '내', meaning: '이에, 곧', radical: '丿', strokes: 2 },
  '亦': { eumhun: '역', meaning: '또한', radical: '亠', strokes: 6 },
  '必': { eumhun: '필', meaning: '반드시', radical: '心', strokes: 5 },
  '當': { eumhun: '당', meaning: '마땅하다', radical: '田', strokes: 13 },
  '皆': { eumhun: '개', meaning: '모두', radical: '白', strokes: 9 },
  '要': { eumhun: '요', meaning: '요긴하다, 구하다', radical: '西', strokes: 9 },
  '又': { eumhun: '우', meaning: '또', radical: '又', strokes: 2 },
  '最': { eumhun: '최', meaning: '가장', radical: '曰', strokes: 12 },
  '甚': { eumhun: '심', meaning: '심하다, 매우', radical: '甘', strokes: 9 },
  '蓋': { eumhun: '개', meaning: '대개, 덮다', radical: '艸', strokes: 13 },
  '故': { eumhun: '고', meaning: '그러므로, 옛', radical: '攴', strokes: 9 },
  '因': { eumhun: '인', meaning: '인하다, 원인', radical: '囗', strokes: 6 },
  '但': { eumhun: '단', meaning: '다만', radical: '人', strokes: 7 },
  '且': { eumhun: '차', meaning: '또, 게다가', radical: '一', strokes: 5 },
  '或': { eumhun: '혹', meaning: '혹, 혹시', radical: '戈', strokes: 8 },
  '即': { eumhun: '즉', meaning: '곧', radical: '卩', strokes: 7 },
  '雖': { eumhun: '수/쇄', meaning: '비록', radical: '隹', strokes: 17 },
  '然': { eumhun: '연', meaning: '그러하다', radical: '火', strokes: 12 },
  '何': { eumhun: '하', meaning: '무엇, 어찌', radical: '人', strokes: 7 },
  '凡': { eumhun: '범', meaning: '무릇, 모든', radical: '几', strokes: 3 },
  '蓋': { eumhun: '개', meaning: '대개', radical: '艸', strokes: 13 },
  '豈': { eumhun: '기', meaning: '어찌', radical: '豆', strokes: 10 },

  // ═══════════════════════════════════════════
  // 동사/형용사 (자평진전 빈출)
  // ═══════════════════════════════════════════
  '見': { eumhun: '견', meaning: '보다', radical: '見', strokes: 7 },
  '知': { eumhun: '지', meaning: '알다', radical: '矢', strokes: 8 },
  '言': { eumhun: '언', meaning: '말, 말하다', radical: '言', strokes: 7 },
  '謂': { eumhun: '위', meaning: '이르다, 말하다', radical: '言', strokes: 16 },
  '曰': { eumhun: '왈', meaning: '가로되, 말하다', radical: '曰', strokes: 4 },
  '問': { eumhun: '문', meaning: '묻다', radical: '口', strokes: 11 },
  '答': { eumhun: '답', meaning: '대답하다', radical: '竹', strokes: 12 },
  '先': { eumhun: '선', meaning: '먼저', radical: '儿', strokes: 6 },
  '後': { eumhun: '후', meaning: '뒤, 나중', radical: '彳', strokes: 9 },
  '上': { eumhun: '상', meaning: '위', radical: '一', strokes: 3 },
  '下': { eumhun: '하', meaning: '아래', radical: '一', strokes: 3 },
  '內': { eumhun: '내', meaning: '안', radical: '入', strokes: 4 },
  '外': { eumhun: '외', meaning: '밖', radical: '夕', strokes: 5 },
  '多': { eumhun: '다', meaning: '많다', radical: '夕', strokes: 6 },
  '少': { eumhun: '소', meaning: '적다', radical: '小', strokes: 4 },
  '強': { eumhun: '강', meaning: '강하다', radical: '弓', strokes: 12 },
  '弱': { eumhun: '약', meaning: '약하다', radical: '弓', strokes: 10 },
  '輕': { eumhun: '경', meaning: '가볍다', radical: '車', strokes: 14 },
  '重': { eumhun: '중', meaning: '무겁다', radical: '里', strokes: 9 },
  '善': { eumhun: '선', meaning: '착하다, 좋다', radical: '口', strokes: 12 },
  '惡': { eumhun: '악/오', meaning: '악하다, 싫어하다', radical: '心', strokes: 12 },
  '吉': { eumhun: '길', meaning: '길하다', radical: '口', strokes: 6, myeongri: '길(吉). 좋은 운. 사주나 운에서 좋은 작용' },
  '凶': { eumhun: '흉', meaning: '흉하다', radical: '凵', strokes: 4, myeongri: '흉(凶). 나쁜 운. 사주나 운에서 나쁜 작용' },
  '貴': { eumhun: '귀', meaning: '귀하다', radical: '貝', strokes: 12, myeongri: '귀(貴). 고귀함. 관직, 높은 지위를 얻는 것' },
  '賤': { eumhun: '천', meaning: '천하다', radical: '貝', strokes: 15, myeongri: '천(賤). 비천함. 낮은 지위' },
  '富': { eumhun: '부', meaning: '부유하다', radical: '宀', strokes: 12, myeongri: '부(富). 부유함. 재물이 풍부한 것' },
  '貧': { eumhun: '빈', meaning: '가난하다', radical: '貝', strokes: 11, myeongri: '빈(貧). 가난함. 재물이 부족한 것' },
  '壽': { eumhun: '수', meaning: '목숨, 오래 살다', radical: '寸', strokes: 14, myeongri: '수(壽). 장수. 오래 사는 것' },
  '夭': { eumhun: '요', meaning: '일찍 죽다', radical: '大', strokes: 4, myeongri: '요(夭). 요절. 일찍 죽는 것' },

  // ═══════════════════════════════════════════
  // 사주 해석 관련
  // ═══════════════════════════════════════════
  '身': { eumhun: '신', meaning: '몸', radical: '身', strokes: 7, myeongri: '신(身). 일간(日干) 자신을 가리킴. 신강(身强)/신약(身弱)' },
  '主': { eumhun: '주', meaning: '주인', radical: '丶', strokes: 5, myeongri: '일주(日主). 일간을 가리키는 말. 사주의 주인공' },
  '元': { eumhun: '원', meaning: '으뜸, 근원', radical: '儿', strokes: 4, myeongri: '일원(日元). 일간을 가리키는 말' },
  '根': { eumhun: '근', meaning: '뿌리', radical: '木', strokes: 10, myeongri: '통근(通根). 천간이 지지에 뿌리를 둠. 힘의 원천' },
  '通': { eumhun: '통', meaning: '통하다', radical: '辵', strokes: 11, myeongri: '통근(通根), 통관(通關). 뿌리가 통하거나 관계가 통함' },
  '關': { eumhun: '관', meaning: '관문, 빗장', radical: '門', strokes: 19, myeongri: '통관(通關). 대립하는 두 오행 사이를 중재하는 오행' },
  '情': { eumhun: '정', meaning: '뜻, 정', radical: '心', strokes: 11, myeongri: '유정(有情)/무정(無情). 사주 글자 간의 친밀한 관계 여부' },
  '力': { eumhun: '력/역', meaning: '힘', radical: '力', strokes: 2, myeongri: '역량, 힘. 일간이나 용신의 힘의 정도' },
  '真': { eumhun: '진', meaning: '참, 진실', radical: '十', strokes: 10, myeongri: '진(眞)의 속자. 참된 것. 진신(真神), 진격(真格)' },
  '假': { eumhun: '가', meaning: '거짓, 빌리다', radical: '人', strokes: 11, myeongri: '가(假). 거짓된 것. 가신(假神), 가격(假格)' },

  // ═══════════════════════════════════════════
  // 특수 명리학 개념
  // ═══════════════════════════════════════════
  '祿': { eumhun: '록', meaning: '녹봉, 복', radical: '示', strokes: 13, myeongri: '록(祿). 녹봉. 천간이 지지에서 임관(臨官)의 위치. 건록격(建祿格)' },
  '建': { eumhun: '건', meaning: '세우다', radical: '廴', strokes: 9, myeongri: '건록(建祿). 월지가 일간의 록이 되는 것. 건록격(建祿格)' },
  '刃': { eumhun: '인', meaning: '칼날', radical: '刀', strokes: 3, myeongri: '양인(陽刃). 일간이 극왕한 상태. 양인격(陽刃格). 강렬한 기운' },
  '殺': { eumhun: '살', meaning: '죽이다', radical: '殳', strokes: 11, myeongri: '칠살(七殺)/편관(偏官). 나를 극하는 같은 음양의 오행. 강한 극' },
  '制': { eumhun: '제', meaning: '만들다, 제어하다', radical: '刀', strokes: 8, myeongri: '제화(制化). 살을 제어함. 식신제살(食神制殺)' },
  '護': { eumhun: '호', meaning: '보호하다', radical: '言', strokes: 20, myeongri: '보호. 용신을 보호하는 역할' },
  '救': { eumhun: '구', meaning: '구하다, 구원하다', radical: '攴', strokes: 11, myeongri: '구응(救應). 위기를 구함. 파격을 막아주는 글자' },
  '損': { eumhun: '손', meaning: '덜다, 손해', radical: '手', strokes: 13, myeongri: '손상. 용신이 손상됨' },
  '益': { eumhun: '익', meaning: '더하다, 이익', radical: '皿', strokes: 10, myeongri: '유익함. 사주에 도움이 되는 작용' },
  '調': { eumhun: '조', meaning: '고르다, 조절하다', radical: '言', strokes: 15, myeongri: '조후(調候). 사주의 한난조습을 조절하는 것. 병약법의 핵심' },
  '候': { eumhun: '후', meaning: '기후, 기다리다', radical: '人', strokes: 10, myeongri: '조후(調候)의 후. 기후. 사주의 온도와 습도 조절' },
  '寒': { eumhun: '한', meaning: '춥다', radical: '宀', strokes: 12, myeongri: '한(寒). 차가움. 겨울에 태어난 사주는 따뜻함이 필요' },
  '暖': { eumhun: '난', meaning: '따뜻하다', radical: '日', strokes: 13, myeongri: '난(暖). 따뜻함. 추운 사주에 필요한 화(火)의 기운' },
  '燥': { eumhun: '조', meaning: '마르다', radical: '火', strokes: 17, myeongri: '조(燥). 건조함. 여름 사주에 나타나는 건조한 기운' },
  '濕': { eumhun: '습', meaning: '습하다', radical: '水', strokes: 17, myeongri: '습(濕). 습함. 수기(水氣)가 많은 사주의 특성' },

  // ═══════════════════════════════════════════
  // 도화/역마/귀인 등 신살 관련
  // ═══════════════════════════════════════════
  '桃': { eumhun: '도', meaning: '복숭아', radical: '木', strokes: 10, myeongri: '도화살(桃花殺). 이성운, 매력, 인기와 관련된 신살' },
  '花': { eumhun: '화', meaning: '꽃', radical: '艸', strokes: 8, myeongri: '도화(桃花)의 화. 꽃처럼 아름답고 매력적인 기운' },
  '驛': { eumhun: '역', meaning: '역, 역참', radical: '馬', strokes: 23, myeongri: '역마살(驛馬殺). 이동, 여행, 변동과 관련된 신살' },
  '馬': { eumhun: '마', meaning: '말', radical: '馬', strokes: 10, myeongri: '역마(驛馬)의 마. 말처럼 움직이는 기운. 변동, 이사, 해외' },
  '貴': { eumhun: '귀', meaning: '귀하다', radical: '貝', strokes: 12, myeongri: '천을귀인(天乙貴人). 가장 좋은 귀인. 위기에서 도움을 받음' },
  '人': { eumhun: '인', meaning: '사람', radical: '人', strokes: 2, myeongri: '귀인(貴人). 도움을 주는 사람/기운' },
  '華': { eumhun: '화', meaning: '빛나다, 꽃', radical: '艸', strokes: 12, myeongri: '화개살(華蓋殺). 예술, 종교, 학문과 관련. 고독, 총명' },
  '蓋': { eumhun: '개', meaning: '덮다', radical: '艸', strokes: 13, myeongri: '화개(華蓋)의 개. 덮개. 하늘을 덮는 화려한 장막' },

  // ═══════════════════════════════════════════
  // 추가 일반 한자 (고전 문장 빈출)
  // ═══════════════════════════════════════════
  '一': { eumhun: '일', meaning: '하나', radical: '一', strokes: 1 },
  '二': { eumhun: '이', meaning: '둘', radical: '二', strokes: 2 },
  '三': { eumhun: '삼', meaning: '셋', radical: '一', strokes: 3 },
  '五': { eumhun: '오', meaning: '다섯', radical: '二', strokes: 4 },
  '六': { eumhun: '육/륙', meaning: '여섯', radical: '八', strokes: 4 },
  '七': { eumhun: '칠', meaning: '일곱', radical: '一', strokes: 2 },
  '九': { eumhun: '구', meaning: '아홉', radical: '丿', strokes: 2 },
  '十': { eumhun: '십', meaning: '열', radical: '十', strokes: 2 },
  '百': { eumhun: '백', meaning: '일백', radical: '白', strokes: 6 },
  '千': { eumhun: '천', meaning: '일천', radical: '十', strokes: 3 },
  '萬': { eumhun: '만', meaning: '일만', radical: '艸', strokes: 13 },
  '人': { eumhun: '인', meaning: '사람', radical: '人', strokes: 2 },
  '物': { eumhun: '물', meaning: '만물, 물건', radical: '牛', strokes: 8 },
  '事': { eumhun: '사', meaning: '일', radical: '亅', strokes: 8 },
  '心': { eumhun: '심', meaning: '마음', radical: '心', strokes: 4 },
  '性': { eumhun: '성', meaning: '성품', radical: '心', strokes: 8 },
  '情': { eumhun: '정', meaning: '뜻, 정', radical: '心', strokes: 11 },
  '意': { eumhun: '의', meaning: '뜻', radical: '心', strokes: 13 },
  '德': { eumhun: '덕', meaning: '덕', radical: '彳', strokes: 15 },
  '道': { eumhun: '도', meaning: '길, 도리', radical: '辵', strokes: 13 },
  '法': { eumhun: '법', meaning: '법, 방법', radical: '水', strokes: 8 },
  '經': { eumhun: '경', meaning: '경전, 지나다', radical: '糸', strokes: 13 },
  '書': { eumhun: '서', meaning: '글, 책', radical: '曰', strokes: 10 },
  '文': { eumhun: '문', meaning: '글월, 무늬', radical: '文', strokes: 4 },
  '章': { eumhun: '장', meaning: '글, 문장', radical: '立', strokes: 11 },
  '名': { eumhun: '명', meaning: '이름', radical: '口', strokes: 6 },
  '義': { eumhun: '의', meaning: '옳다, 의리', radical: '羊', strokes: 13 },
  '仁': { eumhun: '인', meaning: '어질다', radical: '人', strokes: 4 },
  '禮': { eumhun: '례/예', meaning: '예의', radical: '示', strokes: 18 },
  '智': { eumhun: '지', meaning: '지혜', radical: '日', strokes: 12 },
  '信': { eumhun: '신', meaning: '믿다, 믿음', radical: '人', strokes: 9 },

  // ═══════════════════════════════════════════
  // 자연/시간 관련
  // ═══════════════════════════════════════════
  '春': { eumhun: '춘', meaning: '봄', radical: '日', strokes: 9, myeongri: '봄. 목(木)의 계절. 인묘진(寅卯辰)월' },
  '夏': { eumhun: '하', meaning: '여름', radical: '夂', strokes: 10, myeongri: '여름. 화(火)의 계절. 사오미(巳午未)월' },
  '秋': { eumhun: '추', meaning: '가을', radical: '禾', strokes: 9, myeongri: '가을. 금(金)의 계절. 신유술(申酉戌)월' },
  '冬': { eumhun: '동', meaning: '겨울', radical: '冫', strokes: 5, myeongri: '겨울. 수(水)의 계절. 해자축(亥子丑)월' },
  '東': { eumhun: '동', meaning: '동쪽', radical: '木', strokes: 8, myeongri: '동쪽. 목(木)의 방위' },
  '西': { eumhun: '서', meaning: '서쪽', radical: '西', strokes: 6, myeongri: '서쪽. 금(金)의 방위' },
  '南': { eumhun: '남', meaning: '남쪽', radical: '十', strokes: 9, myeongri: '남쪽. 화(火)의 방위' },
  '北': { eumhun: '북', meaning: '북쪽', radical: '匕', strokes: 5, myeongri: '북쪽. 수(水)의 방위' },
  '山': { eumhun: '산', meaning: '산', radical: '山', strokes: 3 },
  '川': { eumhun: '천', meaning: '내, 시내', radical: '川', strokes: 3 },
  '河': { eumhun: '하', meaning: '강', radical: '水', strokes: 8 },
  '海': { eumhun: '해', meaning: '바다', radical: '水', strokes: 10 },
  '風': { eumhun: '풍', meaning: '바람', radical: '風', strokes: 9 },
  '雲': { eumhun: '운', meaning: '구름', radical: '雨', strokes: 12 },
  '雨': { eumhun: '우', meaning: '비', radical: '雨', strokes: 8 },
  '雪': { eumhun: '설', meaning: '눈', radical: '雨', strokes: 11 },
  '霜': { eumhun: '상', meaning: '서리', radical: '雨', strokes: 17 },
  '露': { eumhun: '로/노', meaning: '이슬', radical: '雨', strokes: 21 },
  '雷': { eumhun: '뢰/뇌', meaning: '우레', radical: '雨', strokes: 13 },
  '電': { eumhun: '전', meaning: '번개', radical: '雨', strokes: 13 },

  // ═══════════════════════════════════════════
  // 식물/동물 관련
  // ═══════════════════════════════════════════
  '草': { eumhun: '초', meaning: '풀', radical: '艸', strokes: 9 },
  '林': { eumhun: '림/임', meaning: '수풀', radical: '木', strokes: 8 },
  '森': { eumhun: '삼', meaning: '삼림', radical: '木', strokes: 12 },
  '松': { eumhun: '송', meaning: '소나무', radical: '木', strokes: 8 },
  '竹': { eumhun: '죽', meaning: '대나무', radical: '竹', strokes: 6 },
  '鳥': { eumhun: '조', meaning: '새', radical: '鳥', strokes: 11 },
  '魚': { eumhun: '어', meaning: '물고기', radical: '魚', strokes: 11 },
  '龍': { eumhun: '룡/용', meaning: '용', radical: '龍', strokes: 16 },
  '虎': { eumhun: '호', meaning: '호랑이', radical: '虍', strokes: 8 },
  '鼠': { eumhun: '서', meaning: '쥐', radical: '鼠', strokes: 13 },
  '牛': { eumhun: '우', meaning: '소', radical: '牛', strokes: 4 },
  '兎': { eumhun: '토', meaning: '토끼', radical: '儿', strokes: 7 },
  '蛇': { eumhun: '사', meaning: '뱀', radical: '虫', strokes: 11 },
  '羊': { eumhun: '양', meaning: '양', radical: '羊', strokes: 6 },
  '猴': { eumhun: '후', meaning: '원숭이', radical: '犬', strokes: 12 },
  '鷄': { eumhun: '계', meaning: '닭', radical: '鳥', strokes: 21 },
  '犬': { eumhun: '견', meaning: '개', radical: '犬', strokes: 4 },
  '豬': { eumhun: '저', meaning: '돼지', radical: '豕', strokes: 16 },

  // ═══════════════════════════════════════════
  // 신체/건강 관련
  // ═══════════════════════════════════════════
  '頭': { eumhun: '두', meaning: '머리', radical: '頁', strokes: 16 },
  '目': { eumhun: '목', meaning: '눈', radical: '目', strokes: 5 },
  '耳': { eumhun: '이', meaning: '귀', radical: '耳', strokes: 6 },
  '口': { eumhun: '구', meaning: '입', radical: '口', strokes: 3 },
  '手': { eumhun: '수', meaning: '손', radical: '手', strokes: 4 },
  '足': { eumhun: '족', meaning: '발', radical: '足', strokes: 7 },
  '骨': { eumhun: '골', meaning: '뼈', radical: '骨', strokes: 10 },
  '血': { eumhun: '혈', meaning: '피', radical: '血', strokes: 6 },
  '肉': { eumhun: '육', meaning: '고기, 살', radical: '肉', strokes: 6 },
  '皮': { eumhun: '피', meaning: '가죽, 피부', radical: '皮', strokes: 5 },
  '氣': { eumhun: '기', meaning: '기운', radical: '气', strokes: 10 },

  // ═══════════════════════════════════════════
  // 사회/직업/관직 관련
  // ═══════════════════════════════════════════
  '王': { eumhun: '왕', meaning: '임금', radical: '玉', strokes: 4 },
  '臣': { eumhun: '신', meaning: '신하', radical: '臣', strokes: 7 },
  '將': { eumhun: '장', meaning: '장수', radical: '寸', strokes: 11 },
  '相': { eumhun: '상', meaning: '서로, 재상', radical: '目', strokes: 9 },
  '侯': { eumhun: '후', meaning: '제후', radical: '人', strokes: 9 },
  '公': { eumhun: '공', meaning: '공평하다, 공', radical: '八', strokes: 4 },
  '私': { eumhun: '사', meaning: '사사롭다', radical: '禾', strokes: 7 },
  '民': { eumhun: '민', meaning: '백성', radical: '氏', strokes: 5 },
  '國': { eumhun: '국', meaning: '나라', radical: '囗', strokes: 11 },
  '家': { eumhun: '가', meaning: '집', radical: '宀', strokes: 10 },

  // ═══════════════════════════════════════════
  // 추가 자평진전 빈출 한자
  // ═══════════════════════════════════════════
  '太': { eumhun: '태', meaning: '크다, 매우', radical: '大', strokes: 4 },
  '極': { eumhun: '극', meaning: '극, 끝', radical: '木', strokes: 13 },
  '陰': { eumhun: '음', meaning: '그늘', radical: '阝', strokes: 11 },
  '陽': { eumhun: '양', meaning: '볕', radical: '阝', strokes: 12 },
  '太': { eumhun: '태', meaning: '매우, 크다', radical: '大', strokes: 4, myeongri: '태극(太極). 음양이 나뉘기 전의 상태' },
  '兩': { eumhun: '양', meaning: '둘, 양쪽', radical: '入', strokes: 8 },
  '儀': { eumhun: '의', meaning: '거동, 의식', radical: '人', strokes: 15 },
  '象': { eumhun: '상', meaning: '코끼리, 형상', radical: '豕', strokes: 12 },
  '數': { eumhun: '수', meaning: '셈, 수', radical: '攴', strokes: 15 },
  '理': { eumhun: '리/이', meaning: '이치, 다스리다', radical: '玉', strokes: 11 },
  '氣': { eumhun: '기', meaning: '기운', radical: '气', strokes: 10 },
  '質': { eumhun: '질', meaning: '바탕, 질', radical: '貝', strokes: 15 },
  '形': { eumhun: '형', meaning: '모양', radical: '彡', strokes: 7 },
  '勝': { eumhun: '승', meaning: '이기다', radical: '力', strokes: 12 },
  '負': { eumhun: '부', meaning: '지다, 짊어지다', radical: '貝', strokes: 9 },
  '進': { eumhun: '진', meaning: '나아가다', radical: '辵', strokes: 12 },
  '退': { eumhun: '퇴', meaning: '물러나다', radical: '辵', strokes: 9 },
  '消': { eumhun: '소', meaning: '사라지다', radical: '水', strokes: 10 },
  '長': { eumhun: '장', meaning: '길다, 자라다', radical: '長', strokes: 8 },
  '短': { eumhun: '단', meaning: '짧다', radical: '矢', strokes: 12 },
  '深': { eumhun: '심', meaning: '깊다', radical: '水', strokes: 11 },
  '淺': { eumhun: '천', meaning: '얕다', radical: '水', strokes: 11 },
  '厚': { eumhun: '후', meaning: '두텁다', radical: '厂', strokes: 9 },
  '薄': { eumhun: '박', meaning: '얇다', radical: '艸', strokes: 16 },
  '明': { eumhun: '명', meaning: '밝다', radical: '日', strokes: 8 },
  '暗': { eumhun: '암', meaning: '어둡다', radical: '日', strokes: 13 },
  '動': { eumhun: '동', meaning: '움직이다', radical: '力', strokes: 11 },
  '靜': { eumhun: '정', meaning: '고요하다', radical: '青', strokes: 16 },
  '開': { eumhun: '개', meaning: '열다', radical: '門', strokes: 12 },
  '閉': { eumhun: '폐', meaning: '닫다', radical: '門', strokes: 11 },
  '始': { eumhun: '시', meaning: '비로소', radical: '女', strokes: 8 },
  '終': { eumhun: '종', meaning: '마치다', radical: '糸', strokes: 11 },
  '古': { eumhun: '고', meaning: '옛, 예', radical: '口', strokes: 5 },
  '今': { eumhun: '금', meaning: '이제', radical: '人', strokes: 4 },
  '新': { eumhun: '신', meaning: '새롭다', radical: '斤', strokes: 13 },
  '舊': { eumhun: '구', meaning: '옛, 예전', radical: '臼', strokes: 18 },
  '常': { eumhun: '상', meaning: '항상', radical: '巾', strokes: 11 },
  '異': { eumhun: '이', meaning: '다르다', radical: '田', strokes: 11 },
  '同': { eumhun: '동', meaning: '같다', radical: '口', strokes: 6 },
  '別': { eumhun: '별', meaning: '다르다, 나누다', radical: '刀', strokes: 7 },
  '全': { eumhun: '전', meaning: '온전하다', radical: '入', strokes: 6 },
  '半': { eumhun: '반', meaning: '반', radical: '十', strokes: 5 },
  '分': { eumhun: '분', meaning: '나누다', radical: '刀', strokes: 4 },
  '和': { eumhun: '화', meaning: '화합하다', radical: '口', strokes: 8 },
  '平': { eumhun: '평', meaning: '평평하다', radical: '干', strokes: 5 },
  '正': { eumhun: '정', meaning: '바르다', radical: '止', strokes: 5 },
  '直': { eumhun: '직', meaning: '곧다', radical: '目', strokes: 8 },
  '曲': { eumhun: '곡', meaning: '굽다', radical: '曰', strokes: 6 },
  '方': { eumhun: '방', meaning: '모, 방향', radical: '方', strokes: 4 },
  '圓': { eumhun: '원', meaning: '둥글다', radical: '囗', strokes: 13 },
  '高': { eumhun: '고', meaning: '높다', radical: '高', strokes: 10 },
  '低': { eumhun: '저', meaning: '낮다', radical: '人', strokes: 7 },
  '左': { eumhun: '좌', meaning: '왼쪽', radical: '工', strokes: 5 },
  '右': { eumhun: '우', meaning: '오른쪽', radical: '口', strokes: 5 },
  '前': { eumhun: '전', meaning: '앞', radical: '刀', strokes: 9 },
  '後': { eumhun: '후', meaning: '뒤', radical: '彳', strokes: 9 },
  '裏': { eumhun: '리/이', meaning: '속', radical: '衣', strokes: 13 },
  '表': { eumhun: '표', meaning: '겉, 나타내다', radical: '衣', strokes: 8 },
  '中': { eumhun: '중', meaning: '가운데', radical: '丨', strokes: 4 },
  '間': { eumhun: '간', meaning: '사이', radical: '門', strokes: 12 },
  '遠': { eumhun: '원', meaning: '멀다', radical: '辵', strokes: 14 },
  '近': { eumhun: '근', meaning: '가깝다', radical: '辵', strokes: 7 },
  '來': { eumhun: '래/내', meaning: '오다', radical: '人', strokes: 8 },
  '去': { eumhun: '거', meaning: '가다', radical: '厶', strokes: 5 },
  '入': { eumhun: '입', meaning: '들다', radical: '入', strokes: 2 },
  '出': { eumhun: '출', meaning: '나다', radical: '凵', strokes: 5 },
  '行': { eumhun: '행', meaning: '가다, 행하다', radical: '行', strokes: 6 },
  '止': { eumhun: '지', meaning: '그치다', radical: '止', strokes: 4 },
  '動': { eumhun: '동', meaning: '움직이다', radical: '力', strokes: 11 },
  '作': { eumhun: '작', meaning: '짓다, 만들다', radical: '人', strokes: 7 },
  '起': { eumhun: '기', meaning: '일어나다', radical: '走', strokes: 10 },
  '立': { eumhun: '립/입', meaning: '서다', radical: '立', strokes: 5 },
  '坐': { eumhun: '좌', meaning: '앉다', radical: '土', strokes: 7 },
  '定': { eumhun: '정', meaning: '정하다', radical: '宀', strokes: 8 },
  '安': { eumhun: '안', meaning: '편안하다', radical: '宀', strokes: 6 },
  '危': { eumhun: '위', meaning: '위태하다', radical: '卩', strokes: 6 },
  '存': { eumhun: '존', meaning: '있다, 존재하다', radical: '子', strokes: 6 },
  '亡': { eumhun: '망', meaning: '망하다', radical: '亠', strokes: 3 },
  '盛': { eumhun: '성', meaning: '성하다', radical: '皿', strokes: 12 },
  '衰': { eumhun: '쇠', meaning: '쇠하다', radical: '衣', strokes: 10 },
  '興': { eumhun: '흥', meaning: '일어나다, 흥하다', radical: '臼', strokes: 16 },
  '廢': { eumhun: '폐', meaning: '폐하다', radical: '广', strokes: 15 },
  '榮': { eumhun: '영', meaning: '영화롭다', radical: '木', strokes: 14 },
  '枯': { eumhun: '고', meaning: '마르다', radical: '木', strokes: 9 },
  '茂': { eumhun: '무', meaning: '무성하다', radical: '艸', strokes: 8 },

  // ═══════════════════════════════════════════
  // 자평진전 장(章) 제목 관련
  // ═══════════════════════════════════════════
  '原': { eumhun: '원', meaning: '근원, 원래', radical: '厂', strokes: 10 },
  '配': { eumhun: '배', meaning: '짝, 배합', radical: '酉', strokes: 10 },
  '順': { eumhun: '순', meaning: '순서, 순하다', radical: '頁', strokes: 12 },
  '逆': { eumhun: '역', meaning: '거스르다', radical: '辵', strokes: 10 },
  '雜': { eumhun: '잡', meaning: '섞이다', radical: '隹', strokes: 18, myeongri: '잡기(雜氣). 진술축미(辰戌丑未)의 여러 기운이 섞인 상태' },
  '專': { eumhun: '전', meaning: '오로지', radical: '寸', strokes: 11 },
  '旺': { eumhun: '왕', meaning: '왕성하다', radical: '日', strokes: 8 },
  '衰': { eumhun: '쇠', meaning: '쇠하다', radical: '衣', strokes: 10 },
  '强': { eumhun: '강', meaning: '강하다', radical: '弓', strokes: 11 },
  '弱': { eumhun: '약', meaning: '약하다', radical: '弓', strokes: 10 },

  // ═══════════════════════════════════════════
  // 추가 고전 한문 빈출자
  // ═══════════════════════════════════════════
  '受': { eumhun: '수', meaning: '받다', radical: '又', strokes: 8 },
  '授': { eumhun: '수', meaning: '주다', radical: '手', strokes: 11 },
  '使': { eumhun: '사', meaning: '시키다, 사신', radical: '人', strokes: 8 },
  '令': { eumhun: '령/영', meaning: '시키다, 명령', radical: '人', strokes: 5 },
  '致': { eumhun: '치', meaning: '이르다', radical: '至', strokes: 10 },
  '至': { eumhun: '지', meaning: '이르다', radical: '至', strokes: 6 },
  '及': { eumhun: '급', meaning: '미치다', radical: '又', strokes: 4 },
  '達': { eumhun: '달', meaning: '통달하다', radical: '辵', strokes: 13 },
  '得': { eumhun: '득', meaning: '얻다', radical: '彳', strokes: 11 },
  '失': { eumhun: '실', meaning: '잃다', radical: '大', strokes: 5 },
  '持': { eumhun: '지', meaning: '가지다', radical: '手', strokes: 9 },
  '守': { eumhun: '수', meaning: '지키다', radical: '宀', strokes: 6 },
  '待': { eumhun: '대', meaning: '기다리다', radical: '彳', strokes: 9 },
  '望': { eumhun: '망', meaning: '바라다', radical: '月', strokes: 11 },
  '思': { eumhun: '사', meaning: '생각하다', radical: '心', strokes: 9 },
  '想': { eumhun: '상', meaning: '생각하다', radical: '心', strokes: 13 },
  '念': { eumhun: '념/염', meaning: '생각하다', radical: '心', strokes: 8 },
  '覺': { eumhun: '각', meaning: '깨닫다', radical: '見', strokes: 20 },
  '觀': { eumhun: '관', meaning: '보다', radical: '見', strokes: 25 },
  '察': { eumhun: '찰', meaning: '살피다', radical: '宀', strokes: 14 },
  '辨': { eumhun: '변', meaning: '분별하다', radical: '辛', strokes: 16 },
  '別': { eumhun: '별', meaning: '나누다, 다르다', radical: '刀', strokes: 7 },
  '類': { eumhun: '류/유', meaning: '무리', radical: '頁', strokes: 19 },
  '屬': { eumhun: '속', meaning: '속하다, 무리', radical: '尸', strokes: 21 },

  // ═══════════════════════════════════════════
  // 간지 관련 추가 한자
  // ═══════════════════════════════════════════
  '干': { eumhun: '간', meaning: '줄기, 방패', radical: '干', strokes: 3, myeongri: '천간(天干). 사주의 위쪽 글자' },
  '支': { eumhun: '지', meaning: '가지', radical: '支', strokes: 4, myeongri: '지지(地支). 사주의 아래쪽 글자' },
  '納': { eumhun: '납', meaning: '들이다, 바치다', radical: '糸', strokes: 10, myeongri: '납음(納音). 천간과 지지를 합하여 오행을 정하는 법' },
  '音': { eumhun: '음', meaning: '소리', radical: '音', strokes: 9, myeongri: '납음(納音). 소리의 오행' },
  '空': { eumhun: '공', meaning: '비다', radical: '穴', strokes: 8, myeongri: '공망(空亡). 비어 있는 지지. 그 지지의 작용이 약해짐' },
  '亡': { eumhun: '망', meaning: '망하다', radical: '亠', strokes: 3, myeongri: '공망(空亡). 없어짐' },
  '祿': { eumhun: '록', meaning: '녹, 복', radical: '示', strokes: 13, myeongri: '천간의 록. 천간이 지지에서 가장 왕성한 위치' },
  '馬': { eumhun: '마', meaning: '말', radical: '馬', strokes: 10, myeongri: '역마. 이동, 변동의 신살' },

  // ═══════════════════════════════════════════
  // 자평진전에 자주 등장하는 추가 한자
  // ═══════════════════════════════════════════
  '徐': { eumhun: '서', meaning: '천천히, 성씨', radical: '彳', strokes: 10, myeongri: '서자평(徐子平). 자평명리학의 창시자' },
  '沈': { eumhun: '심', meaning: '잠기다, 성씨', radical: '水', strokes: 7, myeongri: '심효첨(沈孝瞻). 자평진전의 저자' },
  '孝': { eumhun: '효', meaning: '효도', radical: '子', strokes: 7 },
  '任': { eumhun: '임', meaning: '맡기다, 성씨', radical: '人', strokes: 6, myeongri: '임철초(任鐵樵). 적천수의 주석자' },
  '滴': { eumhun: '적', meaning: '물방울', radical: '水', strokes: 14, myeongri: '적천수(滴天髓). 또 다른 명리학 고전' },
  '髓': { eumhun: '수', meaning: '골수', radical: '骨', strokes: 21, myeongri: '적천수(滴天髓). 명리학의 핵심 고전' },
  '窮': { eumhun: '궁', meaning: '다하다, 궁하다', radical: '穴', strokes: 15, myeongri: '궁통보감(窮通寶鑑). 조후법의 대표적 저서' },
  '通': { eumhun: '통', meaning: '통하다', radical: '辵', strokes: 11, myeongri: '궁통보감(窮通寶鑑). 막힌 것을 통함' },
  '寶': { eumhun: '보', meaning: '보배', radical: '宀', strokes: 20, myeongri: '궁통보감(窮通寶鑑). 보배로운 거울' },
  '鑑': { eumhun: '감', meaning: '거울, 비추다', radical: '金', strokes: 22, myeongri: '궁통보감(窮通寶鑑). 살피는 거울' },

  // ═══════════════════════════════════════════
  // 감정/심리 관련
  // ═══════════════════════════════════════════
  '樂': { eumhun: '락/악', meaning: '즐겁다, 음악', radical: '木', strokes: 15 },
  '苦': { eumhun: '고', meaning: '쓰다, 괴롭다', radical: '艸', strokes: 8 },
  '怒': { eumhun: '노', meaning: '성내다', radical: '心', strokes: 9, myeongri: '노(怒). 오지(五志) 중 목(木)의 감정' },
  '恐': { eumhun: '공', meaning: '두려워하다', radical: '心', strokes: 10, myeongri: '공(恐). 오지(五志) 중 수(水)의 감정' },
  '悲': { eumhun: '비', meaning: '슬프다', radical: '心', strokes: 12, myeongri: '비(悲). 오지(五志) 중 금(金)의 감정' },
  '憂': { eumhun: '우', meaning: '근심하다', radical: '心', strokes: 15, myeongri: '우(憂). 토(土)와 관련된 감정' },

  // ═══════════════════════════════════════════
  // 기타 명리학 관련
  // ═══════════════════════════════════════════
  '福': { eumhun: '복', meaning: '복', radical: '示', strokes: 14 },
  '禍': { eumhun: '화', meaning: '재앙', radical: '示', strokes: 14 },
  '災': { eumhun: '재', meaning: '재앙', radical: '火', strokes: 7 },
  '難': { eumhun: '난', meaning: '어렵다', radical: '隹', strokes: 19 },
  '吉': { eumhun: '길', meaning: '길하다', radical: '口', strokes: 6 },
  '凶': { eumhun: '흉', meaning: '흉하다', radical: '凵', strokes: 4 },
  '禎': { eumhun: '정', meaning: '상서롭다', radical: '示', strokes: 14 },
  '瑞': { eumhun: '서', meaning: '상서롭다', radical: '玉', strokes: 13 },
  '忠': { eumhun: '충', meaning: '충성', radical: '心', strokes: 8 },
  '孝': { eumhun: '효', meaning: '효도', radical: '子', strokes: 7 },
  '節': { eumhun: '절', meaning: '마디, 절개', radical: '竹', strokes: 13 },
  '義': { eumhun: '의', meaning: '옳다', radical: '羊', strokes: 13 },
  '廉': { eumhun: '렴/염', meaning: '청렴하다', radical: '广', strokes: 13 },
  '恥': { eumhun: '치', meaning: '부끄러움', radical: '心', strokes: 10 },
  '婚': { eumhun: '혼', meaning: '혼인', radical: '女', strokes: 11, myeongri: '혼인. 남자는 재성(財星), 여자는 관성(官星)으로 봄' },
  '姻': { eumhun: '인', meaning: '인연', radical: '女', strokes: 9 },
  '壽': { eumhun: '수', meaning: '목숨, 오래 살다', radical: '寸', strokes: 14 },
  '夭': { eumhun: '요', meaning: '일찍 죽다', radical: '大', strokes: 4 },
  '祥': { eumhun: '상', meaning: '상서롭다', radical: '示', strokes: 11 },
  '殃': { eumhun: '앙', meaning: '재앙', radical: '歹', strokes: 9 },

  // ═══════════════════════════════════════════
  // 자평진전 본문 빈출 한자 (확장)
  // ═══════════════════════════════════════════
  '會': { eumhun: '회', meaning: '모이다, 모임', radical: '曰', strokes: 13 },
  '的': { eumhun: '적', meaning: '과녁, ~의', radical: '白', strokes: 8 },
  '庫': { eumhun: '고', meaning: '곳간, 창고', radical: '广', strokes: 10, myeongri: '지지의 고지(庫地). 오행이 저장되는 곳. 辰戌丑未가 사고(四庫)' },
  '不': { eumhun: '불/부', meaning: '아니다', radical: '一', strokes: 4 },
  '例': { eumhun: '례', meaning: '법식, 사례', radical: '人', strokes: 8 },
  '在': { eumhun: '재', meaning: '있다, 존재하다', radical: '土', strokes: 6 },
  '淸': { eumhun: '청', meaning: '맑다', radical: '水', strokes: 11 },
  '星': { eumhun: '성', meaning: '별', radical: '日', strokes: 9, myeongri: '신살(神煞)에서 별을 뜻함. 역마성, 화개성 등' },
  '這': { eumhun: '저', meaning: '이, 이것', radical: '辵', strokes: 11 },
  '解': { eumhun: '해', meaning: '풀다, 해석하다', radical: '角', strokes: 13, myeongri: '합이 풀리는 것. 형충파해(刑沖破害)의 해(害)와 구분' },
  '說': { eumhun: '설', meaning: '말하다, 설명하다', radical: '言', strokes: 14 },
  '應': { eumhun: '응', meaning: '응하다, 마땅히', radical: '心', strokes: 17 },
  '提': { eumhun: '제', meaning: '끌어올리다, 제시하다', radical: '手', strokes: 12 },
  '還': { eumhun: '환', meaning: '돌아오다, 도리어', radical: '辵', strokes: 17 },
  '秀': { eumhun: '수', meaning: '빼어나다', radical: '禾', strokes: 7, myeongri: '식신이 생재하여 수려한 격국을 이루는 것' },
  '煞': { eumhun: '살', meaning: '죽이다, 살기', radical: '火', strokes: 13, myeongri: '칠살(七煞)을 뜻함. 편관의 다른 이름. 일간을 극하는 같은 음양의 오행' },
  '就': { eumhun: '취', meaning: '나아가다, 이루다', radical: '尢', strokes: 12 },
  '份': { eumhun: '분', meaning: '나누다, 몫', radical: '人', strokes: 6 },
  '拱': { eumhun: '공', meaning: '두 손 모으다, 공손하다', radical: '手', strokes: 9, myeongri: '암합(暗合)의 일종. 공록(拱祿), 공귀(拱貴)' },
  '佩': { eumhun: '패', meaning: '차다, 패물', radical: '人', strokes: 8 },
  '看': { eumhun: '간', meaning: '보다', radical: '目', strokes: 9 },
  '個': { eumhun: '개', meaning: '낱, 개수', radical: '人', strokes: 10 },
  '並': { eumhun: '병', meaning: '나란히, 아울러', radical: '一', strokes: 8 },
  '否': { eumhun: '부/비', meaning: '아니다, 막히다', radical: '口', strokes: 7, myeongri: '비괘(否卦). 하늘과 땅이 소통하지 못하는 상태' },
  '純': { eumhun: '순', meaning: '순수하다', radical: '糸', strokes: 10, myeongri: '한 가지 오행으로만 이루어진 것. 순금, 순수' },
  '逢': { eumhun: '봉', meaning: '만나다', radical: '辵', strokes: 11 },
  '釋': { eumhun: '석', meaning: '풀다, 놓다', radical: '釆', strokes: 20 },
  '參': { eumhun: '삼/참', meaning: '참여하다, 셋', radical: '厶', strokes: 11 },
  '了': { eumhun: '료', meaning: '마치다, 알다', radical: '亅', strokes: 2 },
  '兩': { eumhun: '량', meaning: '둘, 양쪽', radical: '八', strokes: 8 },
  '六': { eumhun: '육', meaning: '여섯', radical: '八', strokes: 4, myeongri: '육합(六合), 육충(六沖), 육해(六害)의 여섯' },
  '遙': { eumhun: '요', meaning: '멀다', radical: '辵', strokes: 14 },
  '僅': { eumhun: '근', meaning: '겨우, 다만', radical: '人', strokes: 13 },
  '扶': { eumhun: '부', meaning: '돕다, 부축하다', radical: '手', strokes: 7, myeongri: '부억용신(扶抑用神). 약한 것을 부축하고 강한 것을 억제함' },
  '歸': { eumhun: '귀', meaning: '돌아가다', radical: '止', strokes: 18 },
  '到': { eumhun: '도', meaning: '이르다', radical: '刀', strokes: 8 },
  '按': { eumhun: '안', meaning: '누르다, 살피다', radical: '手', strokes: 9 },
  '樣': { eumhun: '양', meaning: '모양', radical: '木', strokes: 15 },
  '許': { eumhun: '허', meaning: '허락하다', radical: '言', strokes: 11 },
  '宮': { eumhun: '궁', meaning: '집, 궁궐', radical: '宀', strokes: 10, myeongri: '사주의 궁(宮). 년주=조상궁, 월주=부모궁, 일주=부부궁, 시주=자녀궁' },
  '依': { eumhun: '의', meaning: '의지하다', radical: '人', strokes: 8 },
  '只': { eumhun: '지', meaning: '다만, 오직', radical: '口', strokes: 5 },
  '沒': { eumhun: '몰', meaning: '빠지다, 없다', radical: '水', strokes: 7 },
  '需': { eumhun: '수', meaning: '필요하다', radical: '雨', strokes: 14 },
  '好': { eumhun: '호', meaning: '좋다', radical: '女', strokes: 6 },
  '他': { eumhun: '타', meaning: '다른, 그', radical: '人', strokes: 5 },
  '剛': { eumhun: '강', meaning: '굳세다', radical: '刀', strokes: 10 },
  '庶': { eumhun: '서', meaning: '여러, 서민', radical: '广', strokes: 11, myeongri: '서민, 일반인. 정관이 아닌 편관과 관련' },
  '回': { eumhun: '회', meaning: '돌다, 돌아오다', radical: '囗', strokes: 6 },
  '裡': { eumhun: '리', meaning: '안, 속', radical: '衣', strokes: 13 },
  '才': { eumhun: '재', meaning: '재주', radical: '手', strokes: 3 },
  '似': { eumhun: '사', meaning: '닮다, 비슷하다', radical: '人', strokes: 7 },
  '休': { eumhun: '휴', meaning: '쉬다', radical: '人', strokes: 6, myeongri: '휴수(休囚). 일간이 쇠퇴하여 힘이 없는 상태' },
  '囚': { eumhun: '수', meaning: '가두다, 죄수', radical: '囗', strokes: 5, myeongri: '휴수(休囚). 일간이 갇혀 힘을 쓰지 못하는 상태' },
  '實': { eumhun: '실', meaning: '열매, 사실', radical: '宀', strokes: 14 },
  '奪': { eumhun: '탈', meaning: '빼앗다', radical: '大', strokes: 14, myeongri: '겁재가 재성을 빼앗는 것. 재를 탈하면 흉' },
  '兼': { eumhun: '겸', meaning: '겸하다, 아울러', radical: '八', strokes: 10 },
  '更': { eumhun: '경/갱', meaning: '다시, 고치다', radical: '曰', strokes: 7 },
  '篇': { eumhun: '편', meaning: '편, 글', radical: '竹', strokes: 15 },
  '綬': { eumhun: '수', meaning: '인끈, 수', radical: '糸', strokes: 14 },
  '府': { eumhun: '부', meaning: '관청, 곳간', radical: '广', strokes: 8 },
  '司': { eumhun: '사', meaning: '맡다, 관청', radical: '口', strokes: 5 },
  '留': { eumhun: '류', meaning: '머무르다', radical: '田', strokes: 10, myeongri: '관성이 머무는 것. 유관(留官)' },
  '秉': { eumhun: '병', meaning: '잡다, 쥐다', radical: '禾', strokes: 8, myeongri: '월령을 병(秉)한다 = 월령의 기운을 장악하다' },
  '面': { eumhun: '면', meaning: '얼굴, 면', radical: '面', strokes: 9 },
  '丞': { eumhun: '승', meaning: '돕다, 벼슬', radical: '一', strokes: 6 },
  '規': { eumhun: '규', meaning: '법, 규칙', radical: '見', strokes: 11 },
  '談': { eumhun: '담', meaning: '말하다', radical: '言', strokes: 15 },
  '梟': { eumhun: '효', meaning: '올빼미', radical: '木', strokes: 11, myeongri: '효신(梟神). 편인의 별칭. 식신을 극하므로 효(올빼미)라 함' },
  '季': { eumhun: '계', meaning: '계절, 끝', radical: '子', strokes: 8, myeongri: '사계절의 끝. 각 계절의 마지막 달' },
  '潤': { eumhun: '윤', meaning: '윤택하다, 적시다', radical: '水', strokes: 15 },
  '張': { eumhun: '장', meaning: '베풀다, 성씨', radical: '弓', strokes: 11 },
  '幇': { eumhun: '방', meaning: '돕다', radical: '巾', strokes: 12 },
  '助': { eumhun: '조', meaning: '돕다', radical: '力', strokes: 7 },
  '加': { eumhun: '가', meaning: '더하다', radical: '力', strokes: 5 },
  '都': { eumhun: '도', meaning: '도읍, 모두', radical: '邑', strokes: 12 },
  '微': { eumhun: '미', meaning: '작다, 미세하다', radical: '彳', strokes: 13 },
  '列': { eumhun: '렬', meaning: '벌이다, 줄', radical: '刀', strokes: 6 },
  '處': { eumhun: '처', meaning: '곳, 처리하다', radical: '虍', strokes: 11 },
  '些': { eumhun: '사', meaning: '조금', radical: '二', strokes: 7 },
  '舉': { eumhun: '거', meaning: '들다, 거행하다', radical: '臼', strokes: 16 },
  '獨': { eumhun: '독', meaning: '홀로', radical: '犬', strokes: 16 },
  '題': { eumhun: '제', meaning: '제목, 문제', radical: '頁', strokes: 18 },
  '藥': { eumhun: '약', meaning: '약', radical: '艸', strokes: 19, myeongri: '용신을 약에 비유. 사주의 병을 치료하는 용신' },
  '脫': { eumhun: '탈', meaning: '벗다, 벗어나다', radical: '肉', strokes: 11 },
  '引': { eumhun: '인', meaning: '끌다, 인용하다', radical: '弓', strokes: 4 },
  '小': { eumhun: '소', meaning: '작다', radical: '小', strokes: 3 },
  '次': { eumhun: '차', meaning: '다음, 차례', radical: '欠', strokes: 6 },
  '位': { eumhun: '위', meaning: '자리, 위치', radical: '人', strokes: 7 },
  '雙': { eumhun: '쌍', meaning: '쌍, 둘', radical: '隹', strokes: 18 },
  '棄': { eumhun: '기', meaning: '버리다', radical: '木', strokes: 12 },
  '抑': { eumhun: '억', meaning: '누르다, 억제하다', radical: '手', strokes: 7, myeongri: '부억용신(扶抑用神). 강한 것을 억제하는 용신' },
  '奇': { eumhun: '기', meaning: '기이하다', radical: '大', strokes: 8 },
  '統': { eumhun: '통', meaning: '거느리다, 통솔하다', radical: '糸', strokes: 12 },
  '除': { eumhun: '제', meaning: '덜다, 제거하다', radical: '阜', strokes: 10 },
  '交': { eumhun: '교', meaning: '사귀다, 교차하다', radical: '亠', strokes: 6 },
  '孤': { eumhun: '고', meaning: '외롭다, 고아', radical: '子', strokes: 8, myeongri: '고진(孤辰). 배우자궁이 비어있는 신살' },
  '祿': { eumhun: '록', meaning: '봉록, 복록', radical: '示', strokes: 13, myeongri: '천간의 녹(祿). 천간이 임관지에 해당하는 지지를 만나는 것. 甲의 록은 寅' },
  '政': { eumhun: '정', meaning: '정치, 다스리다', radical: '攵', strokes: 9 },
  '疑': { eumhun: '의', meaning: '의심하다', radical: '疋', strokes: 14 },
  '求': { eumhun: '구', meaning: '구하다', radical: '水', strokes: 7 },
  '對': { eumhun: '대', meaning: '대하다, 맞다', radical: '寸', strokes: 14 },
  '麼': { eumhun: '마', meaning: '어찌, 작다', radical: '麻', strokes: 14 },
  '反': { eumhun: '반', meaning: '돌이키다, 반대', radical: '又', strokes: 4 },
  '混': { eumhun: '혼', meaning: '섞다, 흐리다', radical: '水', strokes: 11, myeongri: '잡기(雜氣). 여러 오행이 뒤섞인 상태' },
  '附': { eumhun: '부', meaning: '붙다', radical: '阜', strokes: 8 },
  '老': { eumhun: '노', meaning: '늙다', radical: '老', strokes: 6 },
  '乘': { eumhun: '승', meaning: '타다', radical: '丿', strokes: 10 },
  '坤': { eumhun: '곤', meaning: '땅, 곤괘', radical: '土', strokes: 8, myeongri: '곤괘(坤卦). 순음(純陰)의 괘. 여성, 어머니를 상징' },
  '寄': { eumhun: '기', meaning: '부치다, 맡기다', radical: '宀', strokes: 11 },
  '爭': { eumhun: '쟁', meaning: '다투다', radical: '爪', strokes: 8 },
  '李': { eumhun: '리', meaning: '오얏, 성씨', radical: '木', strokes: 7 },
  '補': { eumhun: '보', meaning: '기우다, 보충하다', radical: '衣', strokes: 13 },
  '隔': { eumhun: '격', meaning: '사이 두다, 멀다', radical: '阜', strokes: 13 },
  '朝': { eumhun: '조', meaning: '아침, 조정', radical: '月', strokes: 12 },
  '遇': { eumhun: '우', meaning: '만나다', radical: '辵', strokes: 13 },
  '尋': { eumhun: '심', meaning: '찾다', radical: '寸', strokes: 12 },
  '細': { eumhun: '세', meaning: '가늘다', radical: '糸', strokes: 11 },
  '另': { eumhun: '령', meaning: '다른', radical: '口', strokes: 5 },
  '像': { eumhun: '상', meaning: '형상, 닮다', radical: '人', strokes: 14 },
  '式': { eumhun: '식', meaning: '법, 양식', radical: '弋', strokes: 6 },
  '完': { eumhun: '완', meaning: '온전하다', radical: '宀', strokes: 7 },
  '約': { eumhun: '약', meaning: '약속, 대략', radical: '糸', strokes: 9 },
  '技': { eumhun: '기', meaning: '재주, 기술', radical: '手', strokes: 7 },
  '柔': { eumhun: '유', meaning: '부드럽다', radical: '木', strokes: 9, myeongri: '을목(乙木)의 성질. 부드럽고 유연함' },
  '虛': { eumhun: '허', meaning: '비다, 허무하다', radical: '虍', strokes: 12 },
  '商': { eumhun: '상', meaning: '장사, 상의하다', radical: '口', strokes: 11 },
  '美': { eumhun: '미', meaning: '아름답다', radical: '羊', strokes: 9 },
  '壯': { eumhun: '장', meaning: '씩씩하다, 장년', radical: '士', strokes: 7 },
  '門': { eumhun: '문', meaning: '문', radical: '門', strokes: 8 },
  '江': { eumhun: '강', meaning: '강', radical: '水', strokes: 6 },
  '過': { eumhun: '과', meaning: '지나다, 지나치다', radical: '辵', strokes: 13 },
  '郡': { eumhun: '군', meaning: '고을', radical: '邑', strokes: 10 },
  '尙': { eumhun: '상', meaning: '오히려, 숭상하다', radical: '小', strokes: 8 },
  '衝': { eumhun: '충', meaning: '찌르다, 부딪치다', radical: '行', strokes: 15, myeongri: '충(沖/衝). 서로 맞부딪치는 것. 지지충' },
  '貪': { eumhun: '탐', meaning: '탐하다', radical: '貝', strokes: 11, myeongri: '탐합(貪合). 합에 빠져 본래 역할을 잊는 것. 탐합망살(貪合忘煞)' },
  '夾': { eumhun: '협', meaning: '끼다, 사이에 두다', radical: '大', strokes: 7 },
  '代': { eumhun: '대', meaning: '대신하다', radical: '人', strokes: 5 },
  '挾': { eumhun: '협', meaning: '끼다, 품다', radical: '手', strokes: 10 },
  '等': { eumhun: '등', meaning: '같다, 등급', radical: '竹', strokes: 12 },
  '推': { eumhun: '추', meaning: '밀다, 추론하다', radical: '手', strokes: 11 },
  '部': { eumhun: '부', meaning: '거느리다, 부분', radical: '邑', strokes: 11 },
  '讀': { eumhun: '독', meaning: '읽다', radical: '言', strokes: 22 },
  '稍': { eumhun: '초', meaning: '조금, 약간', radical: '禾', strokes: 12 },
  '已': { eumhun: '이', meaning: '이미', radical: '己', strokes: 3 },
  '較': { eumhun: '교', meaning: '비교하다', radical: '車', strokes: 13 },
  '很': { eumhun: '흔', meaning: '매우', radical: '彳', strokes: 9 },
  '縣': { eumhun: '현', meaning: '고을', radical: '糸', strokes: 16 },
  '顯': { eumhun: '현', meaning: '나타나다, 드러나다', radical: '頁', strokes: 23 },
  '艮': { eumhun: '간', meaning: '그치다, 간괘', radical: '艮', strokes: 6, myeongri: '간괘(艮卦). 산을 상징. 멈추다' },
  '固': { eumhun: '고', meaning: '굳다', radical: '囗', strokes: 8 },
  '圖': { eumhun: '도', meaning: '그림, 꾀하다', radical: '囗', strokes: 14 },
  '造': { eumhun: '조', meaning: '만들다', radical: '辵', strokes: 11 },
  '發': { eumhun: '발', meaning: '쏘다, 나타나다', radical: '癶', strokes: 12 },
  '堂': { eumhun: '당', meaning: '집, 큰 방', radical: '土', strokes: 11 },
  '炎': { eumhun: '염', meaning: '불꽃', radical: '火', strokes: 8, myeongri: '화기(火氣)가 타오르는 것. 염상격(炎上格)' },
  '倒': { eumhun: '도', meaning: '넘어지다, 거꾸로', radical: '人', strokes: 10 },
  '井': { eumhun: '정', meaning: '우물', radical: '二', strokes: 4, myeongri: '정란차(井欄叉). 외격의 일종' },
  '測': { eumhun: '측', meaning: '헤아리다', radical: '水', strokes: 12 },
  '趙': { eumhun: '조', meaning: '성씨', radical: '走', strokes: 14 },
  '閣': { eumhun: '각', meaning: '누각, 집', radical: '門', strokes: 14 },
  '特': { eumhun: '특', meaning: '특별하다', radical: '牛', strokes: 10 },
  '證': { eumhun: '증', meaning: '증거', radical: '言', strokes: 19 },
  '算': { eumhun: '산', meaning: '셈하다', radical: '竹', strokes: 14 },
  '量': { eumhun: '량', meaning: '헤아리다, 분량', radical: '里', strokes: 12 },
  '導': { eumhun: '도', meaning: '이끌다', radical: '寸', strokes: 15 },
  '那': { eumhun: '나', meaning: '어찌, 그', radical: '邑', strokes: 7 },
  '找': { eumhun: '조', meaning: '찾다', radical: '手', strokes: 7 },
  '借': { eumhun: '차', meaning: '빌다', radical: '人', strokes: 10 },
  '際': { eumhun: '제', meaning: '즈음, 사이', radical: '阜', strokes: 14 },
  '枝': { eumhun: '지', meaning: '가지', radical: '木', strokes: 8 },
  '葉': { eumhun: '엽', meaning: '잎', radical: '艸', strokes: 13 },
  '宣': { eumhun: '선', meaning: '베풀다, 선포하다', radical: '宀', strokes: 9 },
  '初': { eumhun: '초', meaning: '처음', radical: '刀', strokes: 7 },
  '卦': { eumhun: '괘', meaning: '점괘', radical: '卜', strokes: 8 },
  '乾': { eumhun: '건', meaning: '하늘, 건괘', radical: '乙', strokes: 11, myeongri: '건괘(乾卦). 순양(純陽)의 괘. 하늘, 아버지, 임금을 상징' },
  '肅': { eumhun: '숙', meaning: '엄숙하다', radical: '聿', strokes: 13 },
  '靈': { eumhun: '령', meaning: '신령, 영혼', radical: '雨', strokes: 24 },
  '兌': { eumhun: '태', meaning: '기쁘다, 태괘', radical: '儿', strokes: 7, myeongri: '태괘(兌卦). 연못을 상징. 금(金)의 성질' },
  '利': { eumhun: '리', meaning: '이롭다', radical: '刀', strokes: 7 },
  '御': { eumhun: '어', meaning: '거느리다, 막다', radical: '彳', strokes: 12 },
  '立': { eumhun: '립', meaning: '서다', radical: '立', strokes: 5 },
  '震': { eumhun: '진', meaning: '우레, 진괘', radical: '雨', strokes: 15, myeongri: '진괘(震卦). 우레를 상징. 목(木)의 성질' },
  '臨': { eumhun: '림', meaning: '임하다', radical: '臣', strokes: 17, myeongri: '십이운성의 임관(臨官). 관직에 임하는 단계. 성장기의 정점' },
  '乎': { eumhun: '호', meaning: '어조사', radical: '丿', strokes: 5 },
  '種': { eumhun: '종', meaning: '씨앗, 종류', radical: '禾', strokes: 14 },
  '親': { eumhun: '친', meaning: '친하다', radical: '見', strokes: 16 },
  '督': { eumhun: '독', meaning: '감독하다', radical: '目', strokes: 13 },
  '稼': { eumhun: '가', meaning: '심다, 곡식', radical: '禾', strokes: 15, myeongri: '가색(稼穡). 토(土)의 특성. 씨를 뿌리고(稼) 거두는(穡) 것' },
  '穡': { eumhun: '색', meaning: '거두다', radical: '禾', strokes: 18, myeongri: '가색(稼穡). 토(土)의 특성. 곡식을 거두는 것' },
  '武': { eumhun: '무', meaning: '무예, 굳세다', radical: '止', strokes: 8 },
  '考': { eumhun: '고', meaning: '생각하다, 아버지', radical: '老', strokes: 6 },
  '停': { eumhun: '정', meaning: '머무르다', radical: '人', strokes: 11 },
  '綱': { eumhun: '강', meaning: '벼리, 큰 줄', radical: '糸', strokes: 14 },
  '謀': { eumhun: '모', meaning: '꾀하다', radical: '言', strokes: 16 },
  '冷': { eumhun: '냉', meaning: '차갑다', radical: '冫', strokes: 7 },
  '賦': { eumhun: '부', meaning: '세금, 타고나다', radical: '貝', strokes: 15 },
  '欄': { eumhun: '란', meaning: '난간', radical: '木', strokes: 21 },
  '焦': { eumhun: '초', meaning: '타다, 초조하다', radical: '火', strokes: 12 },
  '總': { eumhun: '총', meaning: '모두, 거느리다', radical: '糸', strokes: 17 },
  '士': { eumhun: '사', meaning: '선비', radical: '士', strokes: 3 },
  '源': { eumhun: '원', meaning: '근원', radical: '水', strokes: 13 },
  '翻': { eumhun: '번', meaning: '뒤집다', radical: '羽', strokes: 18 },
  '注': { eumhun: '주', meaning: '붓다, 주석', radical: '水', strokes: 8 },
  '既': { eumhun: '기', meaning: '이미', radical: '旡', strokes: 11 },
  '概': { eumhun: '개', meaning: '대략', radical: '木', strokes: 13 },
  '結': { eumhun: '결', meaning: '맺다', radical: '糸', strokes: 12 },
  '斷': { eumhun: '단', meaning: '끊다, 결정하다', radical: '斤', strokes: 18 },
  '恰': { eumhun: '흡', meaning: '꼭, 마침', radical: '心', strokes: 9 },
  '述': { eumhun: '술', meaning: '말하다, 서술하다', radical: '辵', strokes: 8 },
  '矣': { eumhun: '의', meaning: '어조사', radical: '矢', strokes: 7 },
  '氏': { eumhun: '씨', meaning: '성씨', radical: '氏', strokes: 4 },
  '序': { eumhun: '서', meaning: '차례, 서문', radical: '广', strokes: 7 },
  '便': { eumhun: '편', meaning: '편하다', radical: '人', strokes: 9 },
  '徵': { eumhun: '징', meaning: '부르다, 징조', radical: '彳', strokes: 15 },
  '吳': { eumhun: '오', meaning: '성씨', radical: '口', strokes: 7 },
  '芳': { eumhun: '방', meaning: '꽃다움, 향기', radical: '艸', strokes: 8 },
  '閻': { eumhun: '염', meaning: '마을, 성씨', radical: '門', strokes: 16 },
  '容': { eumhun: '용', meaning: '얼굴, 용납하다', radical: '宀', strokes: 10 },
  '騎': { eumhun: '기', meaning: '말 타다', radical: '馬', strokes: 18 },
  '繫': { eumhun: '계', meaning: '매다, 잇다', radical: '糸', strokes: 19 },
  '滅': { eumhun: '멸', meaning: '없어지다', radical: '水', strokes: 13 },
  '鄕': { eumhun: '향', meaning: '고향', radical: '邑', strokes: 13 },
  '晦': { eumhun: '회', meaning: '그믐, 어둡다', radical: '日', strokes: 11 },
  '融': { eumhun: '융', meaning: '녹다, 화합하다', radical: '虫', strokes: 16 },
  '易': { eumhun: '역/이', meaning: '바꾸다, 쉽다', radical: '日', strokes: 8 },
  '宜': { eumhun: '의', meaning: '마땅하다', radical: '宀', strokes: 8 },
  '卑': { eumhun: '비', meaning: '낮다', radical: '十', strokes: 8 },
  '溫': { eumhun: '온', meaning: '따뜻하다', radical: '水', strokes: 13 },
  '濟': { eumhun: '제', meaning: '건너다, 구제하다', radical: '水', strokes: 18 },
  '泄': { eumhun: '설', meaning: '새다, 누설하다', radical: '水', strokes: 8, myeongri: '설기(泄氣). 기운이 새어 빠지는 것. 식상이 일간의 기운을 빼내는 것' },
  '周': { eumhun: '주', meaning: '두루, 주나라', radical: '口', strokes: 8 },
  '淮': { eumhun: '회', meaning: '강 이름', radical: '水', strokes: 12 },
  '離': { eumhun: '리', meaning: '떠나다, 이괘', radical: '隹', strokes: 19, myeongri: '이괘(離卦). 불을 상징. 밝음, 아름다움' },
  '坎': { eumhun: '감', meaning: '구덩이, 감괘', radical: '土', strokes: 7, myeongri: '감괘(坎卦). 물을 상징. 험난함, 지혜' },
  '針': { eumhun: '침', meaning: '바늘', radical: '金', strokes: 10 },
  '術': { eumhun: '술', meaning: '재주, 방법', radical: '行', strokes: 11 },
  '收': { eumhun: '수', meaning: '거두다', radical: '攵', strokes: 6 },
  '隅': { eumhun: '우', meaning: '모퉁이', radical: '阜', strokes: 12 },
  '忘': { eumhun: '망', meaning: '잊다', radical: '心', strokes: 7, myeongri: '탐합망살(貪合忘煞). 합에 빠져 칠살을 잊는 것' },
  '段': { eumhun: '단', meaning: '구분, 단락', radical: '殳', strokes: 9 },
  '竝': { eumhun: '병', meaning: '나란히', radical: '立', strokes: 10 },
  '度': { eumhun: '도', meaning: '헤아리다, 법도', radical: '广', strokes: 9 },
  '互': { eumhun: '호', meaning: '서로', radical: '二', strokes: 4 },
  '朱': { eumhun: '주', meaning: '붉다, 성씨', radical: '木', strokes: 6 },
  '林': { eumhun: '림', meaning: '수풀, 성씨', radical: '木', strokes: 8 },
  '疏': { eumhun: '소', meaning: '성기다, 트이다', radical: '疋', strokes: 12 },
  '劉': { eumhun: '류', meaning: '성씨', radical: '刀', strokes: 15 },
  '岳': { eumhun: '악', meaning: '큰 산', radical: '山', strokes: 8 },
  '伏': { eumhun: '복', meaning: '엎드리다, 숨다', radical: '人', strokes: 6, myeongri: '복음(伏吟). 같은 글자가 겹치는 것. 대운과 사주가 같은 간지일 때' },
  '群': { eumhun: '군', meaning: '무리', radical: '羊', strokes: 13 },
  '判': { eumhun: '판', meaning: '가르다, 판단하다', radical: '刀', strokes: 7 },
  '焚': { eumhun: '분', meaning: '불사르다', radical: '火', strokes: 12 },
  '涵': { eumhun: '함', meaning: '잠기다, 포용하다', radical: '水', strokes: 12 },
  '兒': { eumhun: '아', meaning: '아이', radical: '儿', strokes: 8 },
  '壞': { eumhun: '괴', meaning: '무너지다', radical: '土', strokes: 19 },
  '充': { eumhun: '충', meaning: '채우다', radical: '儿', strokes: 6 },
  '業': { eumhun: '업', meaning: '일, 업', radical: '木', strokes: 13 },
  '歌': { eumhun: '가', meaning: '노래', radical: '欠', strokes: 14 },
  '訣': { eumhun: '결', meaning: '결별, 비결', radical: '言', strokes: 11 },
  '旬': { eumhun: '순', meaning: '열흘', radical: '日', strokes: 6 },
  '品': { eumhun: '품', meaning: '물건, 등급', radical: '口', strokes: 9 },
  '君': { eumhun: '군', meaning: '임금', radical: '口', strokes: 7 },
  '路': { eumhun: '로', meaning: '길', radical: '足', strokes: 13 },
  '浙': { eumhun: '절', meaning: '강 이름', radical: '水', strokes: 10 },
  '案': { eumhun: '안', meaning: '책상, 안건', radical: '木', strokes: 10 },
  '伯': { eumhun: '백', meaning: '맏이, 우두머리', radical: '人', strokes: 7 },
  '汪': { eumhun: '왕', meaning: '넓다, 성씨', radical: '水', strokes: 7 },
  '侍': { eumhun: '시', meaning: '모시다', radical: '人', strokes: 8 },
  '郞': { eumhun: '랑', meaning: '사내', radical: '邑', strokes: 10 },
  '誤': { eumhun: '오', meaning: '그르치다', radical: '言', strokes: 14 },
  '余': { eumhun: '여', meaning: '나, 남다', radical: '人', strokes: 7 },
  '羅': { eumhun: '라', meaning: '벌이다, 그물', radical: '网', strokes: 19 },
  '載': { eumhun: '재', meaning: '싣다, 기록하다', radical: '車', strokes: 13 },
  '隨': { eumhun: '수', meaning: '따르다', radical: '阜', strokes: 17 },
  '叉': { eumhun: '차', meaning: '갈래', radical: '又', strokes: 3 },
  '閱': { eumhun: '열', meaning: '살피다', radical: '門', strokes: 15 },
  '籍': { eumhun: '적', meaning: '문서, 호적', radical: '竹', strokes: 20 },
  '步': { eumhun: '보', meaning: '걸음', radical: '止', strokes: 7 },
  '習': { eumhun: '습', meaning: '익히다', radical: '羽', strokes: 11 },
  '錄': { eumhun: '록', meaning: '기록하다', radical: '金', strokes: 16 },
  '儘': { eumhun: '진', meaning: '다하다', radical: '人', strokes: 16 },
  '辦': { eumhun: '판', meaning: '갖추다, 처리하다', radical: '辛', strokes: 16 },
  '現': { eumhun: '현', meaning: '나타나다', radical: '玉', strokes: 11 },
  '劃': { eumhun: '획', meaning: '긋다, 계획하다', radical: '刀', strokes: 14 },
  '接': { eumhun: '접', meaning: '잇다, 만나다', radical: '手', strokes: 11 },
  '第': { eumhun: '제', meaning: '차례', radical: '竹', strokes: 11 },
  '幾': { eumhun: '기', meaning: '몇, 가깝다', radical: '幺', strokes: 12 },
  '麻': { eumhun: '마', meaning: '삼', radical: '麻', strokes: 11 },
  '煩': { eumhun: '번', meaning: '번거롭다', radical: '火', strokes: 13 },
  '礙': { eumhun: '애', meaning: '막다, 방해하다', radical: '石', strokes: 19 },
  '點': { eumhun: '점', meaning: '점', radical: '黑', strokes: 17 },
  '查': { eumhun: '사', meaning: '조사하다', radical: '木', strokes: 9 },
  '再': { eumhun: '재', meaning: '다시', radical: '冂', strokes: 6 },
  '早': { eumhun: '조', meaning: '이르다', radical: '日', strokes: 6 },
  '限': { eumhun: '한', meaning: '한정하다', radical: '阜', strokes: 9 },
  '確': { eumhun: '확', meaning: '확실하다', radical: '石', strokes: 15 },
  '于': { eumhun: '우', meaning: '어조사, ~에', radical: '二', strokes: 3 },
  '影': { eumhun: '영', meaning: '그림자', radical: '彡', strokes: 15 },
  '響': { eumhun: '향', meaning: '울리다', radical: '音', strokes: 20 },
  '須': { eumhun: '수', meaning: '모름지기', radical: '頁', strokes: 12 },
  '鑒': { eumhun: '감', meaning: '거울, 살피다', radical: '金', strokes: 22 },
  '傳': { eumhun: '전', meaning: '전하다', radical: '人', strokes: 13 },
  '軌': { eumhun: '궤', meaning: '바퀴자국', radical: '車', strokes: 9 },
  '旨': { eumhun: '지', meaning: '뜻', radical: '日', strokes: 6 },
  '轉': { eumhun: '전', meaning: '구르다, 옮기다', radical: '車', strokes: 18 },
  '布': { eumhun: '포', meaning: '베, 펴다', radical: '巾', strokes: 5 },
  '廷': { eumhun: '정', meaning: '조정', radical: '廴', strokes: 7 },
  '英': { eumhun: '영', meaning: '꽃부리, 뛰어나다', radical: '艸', strokes: 9 },
  '俗': { eumhun: '속', meaning: '풍속', radical: '人', strokes: 9 },
  '蕩': { eumhun: '탕', meaning: '물결치다', radical: '艸', strokes: 16 },
  '藤': { eumhun: '등', meaning: '등나무', radical: '艸', strokes: 19 },
  '蘿': { eumhun: '라', meaning: '넝쿨', radical: '艸', strokes: 22 },
  '抱': { eumhun: '포', meaning: '안다', radical: '手', strokes: 8 },
  '烈': { eumhun: '렬', meaning: '세차다', radical: '火', strokes: 10 },
  '衆': { eumhun: '중', meaning: '무리', radical: '血', strokes: 12 },
  '慈': { eumhun: '자', meaning: '사랑하다', radical: '心', strokes: 13 },
  '偶': { eumhun: '우', meaning: '짝, 우연', radical: '人', strokes: 11 },
  '蓄': { eumhun: '축', meaning: '기르다, 모으다', radical: '艸', strokes: 13 },
  '愁': { eumhun: '수', meaning: '근심', radical: '心', strokes: 13 },
  '畏': { eumhun: '외', meaning: '두려워하다', radical: '田', strokes: 9 },
  '光': { eumhun: '광', meaning: '빛', radical: '儿', strokes: 6 },
  '健': { eumhun: '건', meaning: '건강하다', radical: '人', strokes: 11 },
  '斯': { eumhun: '사', meaning: '이, 곧', radical: '斤', strokes: 12 },
  '遁': { eumhun: '둔', meaning: '도망하다, 숨다', radical: '辵', strokes: 13, myeongri: '둔간(遁干). 천간이 숨어 드러나지 않는 것' },
  '盤': { eumhun: '반', meaning: '쟁반, 서리다', radical: '皿', strokes: 15 },
  '屈': { eumhun: '굴', meaning: '굽히다', radical: '尸', strokes: 8 },
  '降': { eumhun: '강', meaning: '내리다', radical: '阜', strokes: 9 },
  '減': { eumhun: '감', meaning: '줄다', radical: '水', strokes: 12 },
  '精': { eumhun: '정', meaning: '정수, 자세하다', radical: '米', strokes: 14 },
  '巨': { eumhun: '거', meaning: '크다', radical: '工', strokes: 5 },
  '集': { eumhun: '집', meaning: '모으다', radical: '隹', strokes: 12 },
  '端': { eumhun: '단', meaning: '끝, 바르다', radical: '立', strokes: 14 },
  '符': { eumhun: '부', meaning: '부적, 부호', radical: '竹', strokes: 11 },
  '鍵': { eumhun: '건', meaning: '열쇠', radical: '金', strokes: 17 },
  '蔡': { eumhun: '채', meaning: '성씨', radical: '艸', strokes: 14 },
  '嚴': { eumhun: '엄', meaning: '엄하다', radical: '口', strokes: 20 },
  '楊': { eumhun: '양', meaning: '버들, 성씨', radical: '木', strokes: 13 },
  '孫': { eumhun: '손', meaning: '손자, 성씨', radical: '子', strokes: 10 },
  '陸': { eumhun: '륙', meaning: '뭍, 성씨', radical: '阜', strokes: 11 },
  '報': { eumhun: '보', meaning: '알리다, 갚다', radical: '土', strokes: 12 },
  '流': { eumhun: '류', meaning: '흐르다', radical: '水', strokes: 10 },
  '妙': { eumhun: '묘', meaning: '묘하다', radical: '女', strokes: 7 },
  '湖': { eumhun: '호', meaning: '호수', radical: '水', strokes: 12 },
  '羈': { eumhun: '기', meaning: '굴레', radical: '网', strokes: 24 },
  '絆': { eumhun: '반', meaning: '얽매다', radical: '糸', strokes: 11 },
  '黃': { eumhun: '황', meaning: '노랗다, 성씨', radical: '黃', strokes: 12 },
  '浮': { eumhun: '부', meaning: '뜨다', radical: '水', strokes: 10 },
  '投': { eumhun: '투', meaning: '던지다', radical: '手', strokes: 7 },
  '滋': { eumhun: '자', meaning: '불어나다', radical: '水', strokes: 12 },
  '宿': { eumhun: '숙', meaning: '잠자다, 별자리', radical: '宀', strokes: 11 },
  '珞': { eumhun: '락', meaning: '구슬', radical: '玉', strokes: 10 },
  '碌': { eumhun: '록', meaning: '돌, 바쁘다', radical: '石', strokes: 13 },
  '息': { eumhun: '식', meaning: '쉬다, 숨', radical: '心', strokes: 10 },
  '台': { eumhun: '대', meaning: '대, 별', radical: '口', strokes: 5 },
  '選': { eumhun: '선', meaning: '가리다', radical: '辵', strokes: 15 },
  '首': { eumhun: '수', meaning: '머리', radical: '首', strokes: 9 },
  '京': { eumhun: '경', meaning: '서울', radical: '亠', strokes: 8 },
  '鬼': { eumhun: '귀', meaning: '귀신', radical: '鬼', strokes: 10, myeongri: '편관(偏官)을 귀(鬼)라 칭하기도 함. 일간을 극하는 것' },
  '權': { eumhun: '권', meaning: '권세', radical: '木', strokes: 22 },
  '鹽': { eumhun: '염', meaning: '소금', radical: '鹵', strokes: 24 },
  '塡': { eumhun: '전', meaning: '메우다', radical: '土', strokes: 13 },
  '凍': { eumhun: '동', meaning: '얼다', radical: '冫', strokes: 10 },
  '薛': { eumhun: '설', meaning: '성씨', radical: '艸', strokes: 17 },
  '賴': { eumhun: '뢰', meaning: '의지하다', radical: '貝', strokes: 16 },
  '輔': { eumhun: '보', meaning: '돕다', radical: '車', strokes: 14 },
  '省': { eumhun: '성/생', meaning: '살피다, 덜다', radical: '目', strokes: 9 },
  '綏': { eumhun: '수', meaning: '편안하다', radical: '糸', strokes: 13 },
  '戶': { eumhun: '호', meaning: '집, 문', radical: '戶', strokes: 4 },
  '謝': { eumhun: '사', meaning: '사례하다, 성씨', radical: '言', strokes: 17 },
  '沈': { eumhun: '침/심', meaning: '잠기다, 성씨', radical: '水', strokes: 7 },
  '班': { eumhun: '반', meaning: '나누다, 반열', radical: '玉', strokes: 10 },
  '胡': { eumhun: '호', meaning: '턱밑, 성씨', radical: '肉', strokes: 9 },
  '戰': { eumhun: '전', meaning: '싸우다', radical: '戈', strokes: 16 },
  '史': { eumhun: '사', meaning: '역사', radical: '口', strokes: 5 },
  '妃': { eumhun: '비', meaning: '왕비', radical: '女', strokes: 6 },
  '穆': { eumhun: '목', meaning: '화목하다', radical: '禾', strokes: 16 },
  '覆': { eumhun: '복', meaning: '덮다, 뒤집다', radical: '西', strokes: 18 },
  '革': { eumhun: '혁', meaning: '가죽, 고치다', radical: '革', strokes: 9 },
  '具': { eumhun: '구', meaning: '갖추다', radical: '八', strokes: 8 },
  '記': { eumhun: '기', meaning: '기록하다', radical: '言', strokes: 10 },
  '給': { eumhun: '급', meaning: '주다', radical: '糸', strokes: 12 },
  '慢': { eumhun: '만', meaning: '게으르다', radical: '心', strokes: 14 },
  '放': { eumhun: '방', meaning: '놓다', radical: '攵', strokes: 8 },
  '置': { eumhun: '치', meaning: '두다', radical: '网', strokes: 13 },
  '討': { eumhun: '토', meaning: '치다, 토론하다', radical: '言', strokes: 10 },
  '由': { eumhun: '유', meaning: '말미암다', radical: '田', strokes: 5 },
  '踐': { eumhun: '천', meaning: '밟다', radical: '足', strokes: 15 },
  '做': { eumhun: '주', meaning: '하다, 만들다', radical: '人', strokes: 11 },
  '我': { eumhun: '아', meaning: '나', radical: '戈', strokes: 7 },
  '範': { eumhun: '범', meaning: '법, 본보기', radical: '竹', strokes: 15 },
  '圍': { eumhun: '위', meaning: '에워싸다', radical: '囗', strokes: 12 },
  '各': { eumhun: '각', meaning: '각각', radical: '口', strokes: 6 },
  '套': { eumhun: '투', meaning: '씌우다', radical: '大', strokes: 10 },
  '突': { eumhun: '돌', meaning: '갑자기, 뚫다', radical: '穴', strokes: 9 },
  '嶽': { eumhun: '악', meaning: '큰 산', radical: '山', strokes: 17 },
  '什': { eumhun: '십', meaning: '열, 무엇', radical: '人', strokes: 4 },
  '瞭': { eumhun: '료', meaning: '분명하다', radical: '目', strokes: 17 },
  '指': { eumhun: '지', meaning: '가리키다', radical: '手', strokes: 9 },
  '仔': { eumhun: '자', meaning: '자세하다', radical: '人', strokes: 5 },
  '猜': { eumhun: '시', meaning: '의심하다', radical: '犬', strokes: 11 },
  '額': { eumhun: '액', meaning: '이마, 액수', radical: '頁', strokes: 18 },
  '況': { eumhun: '황', meaning: '하물며', radical: '水', strokes: 7 },
  '邏': { eumhun: '라', meaning: '순찰하다', radical: '辵', strokes: 22 },
  '輯': { eumhun: '집', meaning: '모으다, 편집', radical: '車', strokes: 16 },
  '卻': { eumhun: '각', meaning: '물리치다', radical: '卩', strokes: 7 },
  '著': { eumhun: '저', meaning: '나타나다, 짓다', radical: '艸', strokes: 12 },
  '狀': { eumhun: '상', meaning: '모양', radical: '犬', strokes: 8 },
  '優': { eumhun: '우', meaning: '넉넉하다', radical: '人', strokes: 17 },
  '殊': { eumhun: '수', meaning: '다르다, 특별하다', radical: '歹', strokes: 10 },
  '淵': { eumhun: '연', meaning: '못, 깊다', radical: '水', strokes: 12 },
  '底': { eumhun: '저', meaning: '밑', radical: '广', strokes: 8 },
  '譬': { eumhun: '비', meaning: '비유하다', radical: '言', strokes: 20 },
  '愈': { eumhun: '유', meaning: '낫다, 더욱', radical: '心', strokes: 13 },
  '驗': { eumhun: '험', meaning: '시험하다', radical: '馬', strokes: 23 },
  '靠': { eumhun: '고', meaning: '기대다', radical: '非', strokes: 15 },
  '複': { eumhun: '복', meaning: '겹치다', radical: '衣', strokes: 14 },
  '被': { eumhun: '피', meaning: '입다, 당하다', radical: '衣', strokes: 10 },
  '果': { eumhun: '과', meaning: '열매, 과연', radical: '木', strokes: 8 },
  '連': { eumhun: '련', meaning: '잇다', radical: '辵', strokes: 11 },
  '期': { eumhun: '기', meaning: '기약하다, 기한', radical: '月', strokes: 12 },
  '域': { eumhun: '역', meaning: '지역', radical: '土', strokes: 11 },
  '詳': { eumhun: '상', meaning: '자세하다', radical: '言', strokes: 13 },
  '遭': { eumhun: '조', meaning: '만나다', radical: '辵', strokes: 15 },
  '石': { eumhun: '석', meaning: '돌', radical: '石', strokes: 5 },
  '田': { eumhun: '전', meaning: '밭', radical: '田', strokes: 5 },
  '承': { eumhun: '승', meaning: '받들다', radical: '手', strokes: 8 },
  '侭': { eumhun: '진', meaning: '다하다', radical: '人', strokes: 8 },
  '涉': { eumhun: '섭', meaning: '건너다', radical: '水', strokes: 10 },
  '憑': { eumhun: '빙', meaning: '기대다, 의지하다', radical: '心', strokes: 16 },
  '垣': { eumhun: '원', meaning: '담', radical: '土', strokes: 9 },
  '照': { eumhun: '조', meaning: '비추다', radical: '火', strokes: 13 },
  '仲': { eumhun: '중', meaning: '둘째, 버금', radical: '人', strokes: 6 },
  '永': { eumhun: '영', meaning: '길다', radical: '水', strokes: 5 },
  '昌': { eumhun: '창', meaning: '창성하다', radical: '日', strokes: 8 },
  '萌': { eumhun: '맹', meaning: '싹트다', radical: '艸', strokes: 12 },
  '芽': { eumhun: '아', meaning: '싹', radical: '艸', strokes: 8 },
  '移': { eumhun: '이', meaning: '옮기다', radical: '禾', strokes: 11 },
  '散': { eumhun: '산', meaning: '흩다', radical: '攵', strokes: 12 },
  '編': { eumhun: '편', meaning: '엮다', radical: '糸', strokes: 15 },
  '錫': { eumhun: '석', meaning: '주석, 베풀다', radical: '金', strokes: 16 },
  '世': { eumhun: '세', meaning: '세상', radical: '一', strokes: 5 },
  '植': { eumhun: '식', meaning: '심다', radical: '木', strokes: 12 },
  '懷': { eumhun: '회', meaning: '품다', radical: '心', strokes: 19 },
  '鳳': { eumhun: '봉', meaning: '봉황', radical: '鳥', strokes: 14 },
  '猛': { eumhun: '맹', meaning: '사납다', radical: '犬', strokes: 11 },
  '欺': { eumhun: '기', meaning: '속이다', radical: '欠', strokes: 12 },
  '翕': { eumhun: '흡', meaning: '합치다, 거두다', radical: '羽', strokes: 12 },
  '闢': { eumhun: '벽', meaning: '열다', radical: '門', strokes: 21 },
  '狂': { eumhun: '광', meaning: '미치다', radical: '犬', strokes: 7 },
  '亢': { eumhun: '항', meaning: '높다, 목', radical: '亠', strokes: 4 },
  '銳': { eumhun: '예', meaning: '날카롭다', radical: '金', strokes: 15 },
  '脆': { eumhun: '취', meaning: '무르다', radical: '肉', strokes: 10 },
  '輸': { eumhun: '수', meaning: '보내다, 지다', radical: '車', strokes: 16 },
  '妹': { eumhun: '매', meaning: '누이', radical: '女', strokes: 8 },
  '軟': { eumhun: '연', meaning: '부드럽다', radical: '車', strokes: 11 },
  '樂': { eumhun: '락', meaning: '즐기다', radical: '木', strokes: 15 },
  '盈': { eumhun: '영', meaning: '가득 차다', radical: '皿', strokes: 9 },
  '社': { eumhun: '사', meaning: '모임, 토지신', radical: '示', strokes: 8 },
  '稷': { eumhun: '직', meaning: '기장, 곡식의 신', radical: '禾', strokes: 15 },
  '滯': { eumhun: '체', meaning: '막히다', radical: '水', strokes: 14 },
  '津': { eumhun: '진', meaning: '나루', radical: '水', strokes: 9 },
  '功': { eumhun: '공', meaning: '공', radical: '力', strokes: 5 },
  '漏': { eumhun: '루', meaning: '새다', radical: '水', strokes: 14 },
  '舒': { eumhun: '서', meaning: '펴다', radical: '舌', strokes: 12 },
  '暢': { eumhun: '창', meaning: '통하다', radical: '日', strokes: 14 },
  '修': { eumhun: '수', meaning: '닦다', radical: '人', strokes: 10 },
  '削': { eumhun: '삭', meaning: '깎다', radical: '刀', strokes: 9 },
  '升': { eumhun: '승', meaning: '오르다', radical: '十', strokes: 4 },
  '覽': { eumhun: '람', meaning: '보다', radical: '見', strokes: 21 },
  '巽': { eumhun: '손', meaning: '공손하다, 손괘', radical: '巳', strokes: 12, myeongri: '손괘(巽卦). 바람을 상징. 목(木)의 성질' },
  '宰': { eumhun: '재', meaning: '재상, 다스리다', radical: '宀', strokes: 10 },
  '野': { eumhun: '야', meaning: '들', radical: '里', strokes: 11 },
  '白': { eumhun: '백', meaning: '흰, 밝다', radical: '白', strokes: 5 },
  '爻': { eumhun: '효', meaning: '점괘의 가로줄', radical: '爻', strokes: 4 },
  '洗': { eumhun: '세', meaning: '씻다', radical: '水', strokes: 9 },
  '器': { eumhun: '기', meaning: '그릇', radical: '口', strokes: 16 },
  '乏': { eumhun: '핍', meaning: '모자라다', radical: '丿', strokes: 5 },
  '勇': { eumhun: '용', meaning: '용감하다', radical: '力', strokes: 9 },
  '材': { eumhun: '재', meaning: '재목', radical: '木', strokes: 7 },
  '斗': { eumhun: '두', meaning: '말(되), 북두', radical: '斗', strokes: 4 },
  '敏': { eumhun: '민', meaning: '민첩하다', radical: '攵', strokes: 11 },
  '曾': { eumhun: '증', meaning: '일찍이', radical: '曰', strokes: 12 },
  '齊': { eumhun: '제', meaning: '가지런하다', radical: '齊', strokes: 14 },
  '封': { eumhun: '봉', meaning: '봉하다', radical: '寸', strokes: 9 },
  '宗': { eumhun: '종', meaning: '마루, 근본', radical: '宀', strokes: 8 },
  '貞': { eumhun: '정', meaning: '곧다, 바르다', radical: '貝', strokes: 9 },
  '迎': { eumhun: '영', meaning: '맞이하다', radical: '辵', strokes: 8 },
  '漢': { eumhun: '한', meaning: '한수, 한나라', radical: '水', strokes: 14 },
  '祖': { eumhun: '조', meaning: '할아버지, 조상', radical: '示', strokes: 10 },
  '活': { eumhun: '활', meaning: '살다', radical: '水', strokes: 9 },
  '監': { eumhun: '감', meaning: '살피다', radical: '皿', strokes: 15 },
  '梁': { eumhun: '량', meaning: '들보', radical: '木', strokes: 11 },
  '錢': { eumhun: '전', meaning: '돈', radical: '金', strokes: 16 },
  '里': { eumhun: '리', meaning: '마을', radical: '里', strokes: 7 },
  '尊': { eumhun: '존', meaning: '높다, 존귀하다', radical: '寸', strokes: 12 },
  '程': { eumhun: '정', meaning: '한도, 법식', radical: '禾', strokes: 12 },
  '潛': { eumhun: '잠', meaning: '잠기다', radical: '水', strokes: 15 },
  '員': { eumhun: '원', meaning: '인원', radical: '口', strokes: 10 },
  '某': { eumhun: '모', meaning: '아무개', radical: '木', strokes: 9 },
  '龍': { eumhun: '룡', meaning: '용', radical: '龍', strokes: 16 },
  '鄭': { eumhun: '정', meaning: '성씨', radical: '邑', strokes: 15 },
  '師': { eumhun: '사', meaning: '스승', radical: '巾', strokes: 10 },
  '兵': { eumhun: '병', meaning: '군사', radical: '八', strokes: 7 },
  '單': { eumhun: '단', meaning: '홑, 하나', radical: '口', strokes: 12 },
  '準': { eumhun: '준', meaning: '기준, 본받다', radical: '水', strokes: 13 },
  '備': { eumhun: '비', meaning: '갖추다', radical: '人', strokes: 12 },
  '久': { eumhun: '구', meaning: '오래다', radical: '丿', strokes: 3 },
  '每': { eumhun: '매', meaning: '매양', radical: '母', strokes: 7 },
  '系': { eumhun: '계', meaning: '이어지다', radical: '糸', strokes: 7 },
  '吾': { eumhun: '오', meaning: '나', radical: '口', strokes: 7 },
  '免': { eumhun: '면', meaning: '벗어나다', radical: '儿', strokes: 7 },
  '追': { eumhun: '추', meaning: '쫓다', radical: '辵', strokes: 10 },
  '區': { eumhun: '구', meaning: '구역', radical: '匚', strokes: 11 },
  '側': { eumhun: '측', meaning: '곁', radical: '人', strokes: 11 },
  '幸': { eumhun: '행', meaning: '다행', radical: '干', strokes: 8 },
  '機': { eumhun: '기', meaning: '틀, 기회', radical: '木', strokes: 16 },
  '層': { eumhun: '층', meaning: '층', radical: '尸', strokes: 15 },
  '簡': { eumhun: '간', meaning: '간단하다', radical: '竹', strokes: 18 },
  '擇': { eumhun: '택', meaning: '가리다', radical: '手', strokes: 17 },
  '增': { eumhun: '증', meaning: '더하다', radical: '土', strokes: 15 },
  '稱': { eumhun: '칭', meaning: '일컫다', radical: '禾', strokes: 14 },
  '均': { eumhun: '균', meaning: '고르다', radical: '土', strokes: 7 },
  '適': { eumhun: '적', meaning: '알맞다, 가다', radical: '辵', strokes: 15 },
  '換': { eumhun: '환', meaning: '바꾸다', radical: '手', strokes: 12 },
  '角': { eumhun: '각', meaning: '뿔, 모서리', radical: '角', strokes: 7 },
  '供': { eumhun: '공', meaning: '이바지하다', radical: '人', strokes: 8 },
  '皇': { eumhun: '황', meaning: '임금', radical: '白', strokes: 9 },
  '脈': { eumhun: '맥', meaning: '핏줄', radical: '肉', strokes: 10 },
  '絡': { eumhun: '락', meaning: '이어지다', radical: '糸', strokes: 12 },
  '亂': { eumhun: '란', meaning: '어지럽다', radical: '乙', strokes: 13 },
  '玉': { eumhun: '옥', meaning: '구슬', radical: '玉', strokes: 5 },
  '創': { eumhun: '창', meaning: '비롯하다', radical: '刀', strokes: 12 },
  '感': { eumhun: '감', meaning: '느끼다', radical: '心', strokes: 13 },
  '審': { eumhun: '심', meaning: '살피다', radical: '宀', strokes: 15 },
  '密': { eumhun: '밀', meaning: '빽빽하다, 비밀', radical: '宀', strokes: 11 },
  '切': { eumhun: '절', meaning: '끊다, 간절하다', radical: '刀', strokes: 4 },
  '析': { eumhun: '석', meaning: '쪼개다, 분석하다', radical: '木', strokes: 8 }
};

// 사전에 없는 한자를 위한 Unicode 기반 기본 정보 제공
function getHanjaInfo(char) {
  if (HANJA_DICT[char]) {
    return HANJA_DICT[char];
  }
  // CJK Unified Ideographs 범위 확인
  const code = char.charCodeAt(0);
  if (code >= 0x4E00 && code <= 0x9FFF) {
    return { eumhun: '(미등록)', meaning: '사전에 없는 한자입니다', radical: '-', strokes: '-' };
  }
  return null;
}

// 한자인지 확인
function isHanja(char) {
  const code = char.charCodeAt(0);
  return (code >= 0x4E00 && code <= 0x9FFF) ||
         (code >= 0x3400 && code <= 0x4DBF) ||
         (code >= 0xF900 && code <= 0xFAFF);
}
